apps/win/slack.talon

Verified shortcuts are the same, not sure if the win folder should be renamed or a new win-linux folder made

Adding linux support for Slack

---

actions/win/app.talon

ctrl-n is new window on Linux and Windows, ctrl-t is tab. They're separate commits so if I've somehow ended up with a weird mapping can just do the os:linux as a PR

Add linux to windows management + fix new tab shortcut

---

apps/linux/terminal.talon
apps/mac/terminal.talon
apps/win/terminal.talon
misc/tabs.talon
text/generic_editor.talon

Add page up/down to allow scrolling in editors
Windows doesn't have tabs so nothing for those
Followed https://support.apple.com/en-gb/guide/terminal/trmlshtcts/mac for shortcuts for mac
It'd be better if "go tab" was part of the generic_browser but I'm not sure how to pass along the number the user says so did it this way for now

Terminal navigation/control

---

misc/git.talon

- add new commands
- use more compact `\n` syntax instead of `<newline>key(enter)` (hopefully this works on Windows; can someone comfirm/test?)
- sort the commands
- add iTerm2 and Terminal

Expand git commands

---

text/generic_editor.talon

This PR adds voice command hooks for indentation to the generic editor. "indent" is pretty straightforward - wasn't sure what people would try for removing indentation, so I left a couple options "indent less" and "out dent". Happy to change the commands if there's feelings about what it should be.

add indentation voice hooks to generic editor

---

code/jetbrains.py

bundle doesn't exist on Linux or Windows. Use it if it does (MacOS) but use name if it doesn't.
Be nice if we can just use name and update the name map to work for MacOS but I don't have a Mac to test with :(

Allow Jetbrains to work on MacOS, Linux and Windows

---

code/keys.py

Previously it was returning only one letter, so saying "uppercase <some
letters here>" would only insert the first letter spoken

Fix user.letters to return a list of letters

---

README.md

I saw this mentioned in slack and thought it'd be useful to include in the docs.
I also made a small change to markdown syntax in setup instructions - multi-line code should look nicer.

add instructions for getting app name or bundle

---

README.md

* remove 'description' in example which doesn't seem necessary for the intended purpose (maybe remnant of earlier api structure?)
* helpful for new folks to be explicit about what an Action is, even if it seems obvious
* note about `user.` prefix seems at home in this section
* added .talon files examples

Fill out some documentation in Actions section

---

apps/mac/password_manager.talon
misc/1password.talon
misc/1password_global.talon

A few changes to bring 1Password more consistent with their published keyboard shortcut documentation:
* 1Password has a keyboard shortcut to fill the password. We can use that rather than implementing ourselves.
* Use shortcut provided by the docs for "password show". I'm not sure where `cmd-shift-x` came from... it doesn't work for me, but maybe @mkandalf can comment on the intent if I'm missing something? IMO, seems best to use the shortcuts provided in the docs unless there's a good reason.
* Use app.bundle() for the context scope as 1Password7 didn't seem to work (I checked "help context" with 1Password in focus and the context wasn't active).
* Only global commands should be in global context and move others to app scoped context. These are grouped based on the 1Password keyboard …

Updates to 1Password: make it more consistent with their published keyboard shortcuts

---

apps/file_manager.talon
code/file_manager.py

The below is triggered unless we setup some mapping on Linux.
Also allow "go pictures" etc to work on XFCE Caja
2020-04-06 15:10:10 ERROR cb error topic="win_focus" cb=<function update_maps at 0x7f05cc7bd710>
20:             lib/python3.7/threading.py:890|
19:             lib/python3.7/threading.py:926|
18:             lib/python3.7/threading.py:870|
17:                 talon/linux/xevents.py:130|
16:                 talon/linux/xevents.py:94 |
15:                 talon/linux/xevents.py:86 |
14:            talon/scripting/dispatch.py:97 |
13:            talon/scripting/dispatch.py:132|
12:            talon/scripting/dispatch.py:123|
11:                talon/scripting/rctx.py:174|
10: ------------------------------------------# 'win_focus' main:_on_event()
9: …

Fix errors for linux file manager

---

code/ide.py

Fixes `actions.list()`.
Before:
```
>>> actions.list()
....
user.ide_rename_file()
Trigger rename file of IDE
user.ide_resize_window_down()
Traceback (most recent call last):
File "<console>", line 1, in <module>
File "talon/scripting/actions.py", line 78, in list
TypeError: can only concatenate str (not "NoneType") to str
>>> 
```
After:
```
>>> actions.list()
....
user.ide_toggle_whitespace()
Hide/Show whitespaces
user.ide_toggle_windowed()
Change windowed mode of view
user.ide_toggle_wrap()
Enable/disable word wrap
user.ide_up_cursor()
Add a cursor above current cursors
>>> 
```

add docstrings for window resizing actions

---

code/code.py

Test on Linux in termite running VIM where the titles are something like `code.py (~/.talon/user/fidget/code) - VIM` which causes the old code not to match correctly.
Confirmed that the `.talon` `code.language` context won't load when editing `code.py` despite `.talon` being in the path, but editing an actual `.talon` file will load it correctly.

change code.language matching so it also works on Linux terminals

---

apps/linux/signal.talon

support for the signal messenger on linux. i suspect the shortcuts might be the same on windows but i've never tried it.

add signal messenger

---

apps/linux/protonmail.talon

i originally had this in its own web/ directory on my fork rather than apps since its technically a website and so the short cuts should roughly match for every system, but i guess the problem is that on mac the control keys will end up being command key. but i think for stuff like this it would be better to have some sort of setting where we say on mac use command key and on everything else use control key and then just have talon figure it out on the fly?

add support for protonmail web application

---

apps/mac/app.talon

I think this broke for some reason after the latest update. This fixed it for me and wanted to share.

fix next/last window not working on mac

---

apps/linux/vscode.talon
apps/vscode.talon

The window class is `Code - OSS` on some Linux distributions (I'm on Solus).

Match open source Visual Studio Code on Linux

---

apps/linux/signal.talon
apps/mac/terminal.talon

This removes duplicate commands as detected from build 1328 on.

Remove duplicate commands

---

code/help.py
misc/help.talon

Adds help search.
The search matches against literal worlds (not captures) in rules. The semantics are AND for all terms, ignoring order.
This also refactors pagination to produce a consistent number of lines for showing commands (either in a context or search view).

Add help search

---

code/numbers.py

this solves the problem described in the code comment. originally aegis proposed that i switch it so that the existing `number` rule contained the new `digits` references, but it seems like that is a problem because of the way the existing scaled function call is done, since we have no easy way to differentiate the `digits` digits and actual `number` digits passed in m. so i opted to change the existing `numbers` rule into a new name. i'm not sure how to create a name that isn't part of the `user.` object prefix, because trying new create one without it would always say that it wasn't defined, which is why it became `user.number_scaled` for now.
anyways i'm happy to change this if you have ideas but definitely way easier to use this number method than the existing one because you can …

better integration of digits and numbers

---

apps/linux/terminal.talon

the switches to using there terminal tag, using the new user.text, and also I move things around to st flags stuff that isn't the actually generic terminal functionality, so should probably be moved to a specific talon file, but I don't know what terminal the person that originally created it used so I can't do it myself .

terminal.talon switch to using user.text and reorder

---

code/jetbrains.py

On ubuntu, I found the name of the app to be jetbrains-studio, without which no commands would work.

Add port mapping for android studio on linux

---

code/app_name_overrides.csv
code/switcher.py

Expands on  the  recognized words to the system  app names overrides that enables focus switching .   By this PR the overides  list is now maintained in a user definable csv file and imported on Talon startup ( In the style of homophones.csv) 
The following TODO is also put in for consideration
**#TODO:** Consider put list csv's (homophones.csv, app_name_overrides.csv) files together in a separate directory,`knausj_talon/lists`

Switcher app name overides as user defined lists

---

code/delayed_speech_off.py

delays turning speech off until after the next phrase is parsed,
so that we don't cut stuff off too soon

add "push to talk" actions for press/release of a button

---

modes/sleep_mode.talon

this change will turn off pop to click when talon is asleep. When I was making the change to enable pop to click even when the eye tracker control mouse is not enabled as described [here](https://github.com/TalonCommunity/Wiki/blob/gh-pages/poptoclick.md) I discovered that pop to click continued to work even when talon was asleep. This fixes it.

turn off pop to click when talon is asleep

---

code/code.py
lang/block_comment.talon
lang/csharp/csharp.talon
lang/go.talon
lang/javascript.talon
lang/operators.talon
lang/programming.talon
lang/python/python.talon
lang/typescript.talon

the main notable change here is typos in operators for dereference and exclusive, as well as fixing some bitwise operator typos unmixed up commands in various language files.
as a result of these changes touching files with some other things I hadn't scent pull requests for, I'm mixing a few other things together:
* `go` to use user.text
* block comments (used by c, but c stuff not PRed yet)
* more extension types
* whitespacing
* null addition for some commands (saying none is not intuitive when using C)

fix a bunch of operator/lang stuff

---

code/switcher.py

- Since the <user.running_applications> capture provides the actual app.name for switching purpose, we only need to do the fuzzier matching if the name isn't already in the list of running apps. In that case, the input is coming from <user.text> in practice. Ugly code, but working.
- For <user.text> input, ignore input < 3 characters
- Add watcher to update overrides when the override file changes. Old overrides appear to stick around for 1 or 2 focus command sometimes, but take affect thereafter.
- Add length check to the CSV processing to prevent silly crashes.

Update switcher.py for reals

---

apps/linux/gdb.talon

simple change moving to `number_small`. a while ago the aegis noted that over optimistic use of `number` can impact performance which starts to accumulate with lots of rules active at once, so i will start moving stuff over that doesn't require huge numbers

to numbers_small

---

code/history.py
misc/history.talon

This is especially useful if you want to have the history always be displayed, in which case you may need to reduce the number of lines displayed to avoid colliding with other windows, which is what I do; this patch lets you reduce the number of lines displayed by default, while retaining a lot of history for debugging.

keep more history, but only show the most recent ten lines by default

---

apps/linux/termite.talon
code/application_matches.py

`and not win.title`  doesn't work within  the `apps.termite`  declaration stuff,  so just moved it back to the termite talon file.  otherwise terminal tag is alway set

fix termite and vim terminal tag

---

misc/mouse.talon

A modest proposal. I've been using this naming for a while now and have had no misrecognition concerns.
Tested on macOS but should be cross platform.

Add middle click "midclick"

---

code/formatters.py

I fixed a bug in formatters.py: rather than keeping the last N formatted phrases, it kept only the first N, and forgot any new entries after that. I also refactored the code a little while I was in there and added a few comments.

fix formatted phrase history bug and clean up a little

---

code/vocabulary.py

Per some discussion in the slack (https://talonvoice.slack.com/archives/G9YTMSZ2T/p1599345924139300), it would be nice if rewriting words Talon already recognizes ("i'm" -> "I'm") didn't change recognition behavior - apparently, adding new words to user.vocabulary makes Talon prefer recognizing them over ordinary words. This PR adjusts vocabulary.py to separate "changing spellings of things Talon recognizes" from "adding new words Talon doesn't recognize".
However, I've only tested this on w2l. Since this affects a pretty core part of knausj_talon, probably it should get tested by someone using Dragon!
I also added capitalization for days of the week & months to the word map.

adjust vocabulary.py to separate word_map from user.vocabulary

---

code/homophones.py

Previously homophones.py was conditionally reading homophones.csv, but unconditionally updating all_homophones and ctx.lists["self.homophones_canonical"], which meant that updates that didn't change homophones.csv would wipe the homophones list.

fix bug in homophones.py that was forgetting all the homophones

---

code/mouse.py
misc/mouse.talon

During testing with talon public v0.1.0, macOS 10.15:
Removed import of `talon.engine`.
mouse.py tries (and fails) to import it, and appears to work fine once removed, no apparent references to `engine`.
Tested functionality of mouse.talon and found "camera overlay" fails:
`KeyError: "Action 'eye_mouse.camera_overlay.toggle' is not declared."` 
I added a corresponding function in mouse.py modeled on the existing control_mouse toggle.
Escaped UpArrow path to match the other Windows cursors listed. I have not been able to test this on Windows.

Mouse fixes for 0.1.0

---

code/formatters.py
misc/formatters.talon
modes/dictation_mode.talon

Small command that reformats the currently selected text.
This implementation strips punctuation before formatting, but it doesn't separate out camel & studley case variables. I can add a heuristic for that if you'd like though.
I also replaced the dictation mode implementation - let me know if I've misinterpreted what that code was doing.
Closes #224

Add command to reformat selected text

---

code/switcher.py
code/window_snap.py
misc/window_management.talon

Shortcuts to snap windows to predefined positions, as well as between
different screens.
Required extracting the "currently running at" logic from
`user.switcher_focus` so the current app is generally accessible. I also
added a timeout and some overt errors to make it a bit cleaner.
Also add the ability to snap named apps.
Closes #217 
Closes #218

Port window snapping commands from Community

---

code/formatters.py
code/keys.py
misc/keys.talon
modes/dictation_mode.talon

I don't think we gain anything from having <user.letters> produce a list instead of a string,  since a string is essentially a list of characters, and each letter should map to a single character. It doesn't look like <user.letters> has been used in very many places in the repo, and I've updated all of them, but people might need to rewrite some of their own custom commands.
I have also added an action `user.insert_formatted`, to insert formatted text, since that seems to be a fairly common thing to need to do.

make <user.letters> produce a string instead of a list

---

code/user_settings.py
code/vocabulary.py

First attempt at pulling Talon lists out into user-defined CSV files.
The system I ended up implementing is a 1:1 mapping between CSV files and Talon dicts. You call a function to tie a Talon list to a CSV file, and it's mirrored from then on. When the CSV is changed, it's reloaded into a list in the `user.user_settings` context (which is active globally). All CSVs are stored in a separate `"settings"` folder, so the user can be track them independently. The API is designed to be simple, calls look like this:
```
bind_list_to_csv(
"user.vocabulary",
"additional_words.csv",
csv_headers=("Word(s)", "Spoken Form (If Different)"),
default_values={"the csv": "will be created", "with these": "values", "if it does not": "exist"},
)
```
The default values are only used when initially creating the …

CSV-based Talon lists

---

code/user_settings.py

The settings folder does actually need to be created up-front. Needs to exist when we start watching the path. This is a quick reversion so it's created ASAP.

Create the settings folder immediately

---

code/ordinals.py

ordinals.py had a bug where it was generating numbers that were off by one for ordinals more than “tenth”. This fixes that bug and simplifies the implementation.

rewrite code/ordinals.py, fixing off by one error

---

lang/c/c.py
lang/c/c.talon
lang/comment.talon
lang/csharp/csharp.py
lang/csharp/csharp.talon
lang/go.talon
lang/programming.talon
lang/python/python.py
lang/python/python.talon
lang/r/r.py
lang/r/r.talon
lang/talon/talon.talon
lang/typescript/typescript.talon

this includes a fix #248, a couple automatic white space changes, a typo in csharp, some additional python stuff for adding docstring documentation as well as type hinting. 
also changed the way the generic library command worked in programmin.talon is because it seems specific to r? now I make it possible in programming.talon to just to add from a list of available includes or libraries or whatever, which makes it a little bit harder to generically do because the terminology differs for different programing languages, so it may be something we don't want generic?

bunch of small language fixes

---

code/edit.py

edit.selected_text has a bug where if there is no selection it returns the current clipboard value. this fixes that bug, per discussion with aegis in slack (https://talonvoice.slack.com/archives/G9YTMSZ2T/p1603817479056200?thread_ts=1603815852.050700&cid=G9YTMSZ2T). I'm a bit worried that we might have some code that depends on this behavior though, so I'd appreciate people testing this out before merging.

fix edit.selected_text to return empty string if there is no selection

---

apps/jetbrains/jetbrains.py

A small change just to add support & ports for Rubymine EAP to `jetbrains` module. Thanks!

Add rubymine EAP to jetbrains module port mapping

---

code/history.py

When a new command is added to the command history window, the `gui.freeze()` calls were making it so the window was not able to be moved

Allow history window to move after history update

---

code/numbers.py
text/numbers.talon

This is a complete rewrite of numbers.py in order to use a simpler grammar as suggested in #249 by lunixbochs, namely a sequence of numbery words optionally separated by "and":
```
<number> ::= {number_word}+ (and {number_word}+)*
```
In the process I've also removed the need to separate the digit parser from the number parser; the number parser handles concatenating digits itself. However, **the behavior of number parsing has changed a bit**. Some slightly strange number phrases like "one thousand one one" (previously 10011, now 1011) or "one hundred thousand and five thousand" (previously 105000, now 100005000) give different results. Take a look at the tests in numbers.py for more examples. If these differences are problematic, let me know what behaviors you need in practice and I can …

overhaul numbers.py to use a simpler grammar

---

code/mouse.py

i believe this is what's intended based on `mouse_scroll_up_continuous`
when scrolling up the setting works but when continuous scroll down the gui is always shown regardless of the setting. this fixes that

check mouse hide setting in scroll down

---

code/keys.py
code/vocabulary.py
misc/formatters.talon
modes/dictation_mode.talon

This patch adds a <user.prose> capture that supports punctuation words like "comma" and "period" and uses it for the `say|speak` command. Things worth noting:
1. My eventual goal is for `<user.prose>` to act like dictation mode, handling auto-capitalization as well. However, for now it only handles punctuation.
2. I previously tried adding punctuation to `user.text`, but decided against it; `<user.text>` is unchanged by this PR. This is for a few reasons. First, sometimes it's handy to be able to speak text without punctuation. Second, adding punctuation to `<user.text>` without also adding auto-capitalization was breaking auto-capitalization in dictation mode (because it was getting parsed as part of the `user.text` capture instead of the dictation mode commands).
3. `phrase` and …

make a user.prose capture that supports punctuation

---

code/keys.py

This binds "menu key" to the menu key on windows and linux (mac does not have this concept). This should implement #296.

add menu key on windows & linux

---

code/formatters.py
misc/formatters.talon

To address #299, this removes sentence as a generic formatter, and adds it as a way to emit capitalized <user.prose>.

add "sentence" as a command for formatting prose, remove as formatter

---

code/exec.py

Without this, the call to `Popen` cannot accept arguments (at least on linux), which makes system_command_nb behave differently and less usefully than system_command.

exec.py: pass shell=True to Popen in system_command_nb

---

apps/linux/dunst.talon

The keybindings ctrl-space and ctrl-shift-space for notifications are not setup
by default on all window managers / desktop environments, so we should use
`dunstctl` for portability.

dunst: use system cmds via dunstctl

---

code/switcher.py

Talon starts faster if you don't use the `talon.ui` module during startup, so this defers it using `app.register("launch", cb)`.
Note that `launch` is only called once after Talon startup, so editing this script is more awkward momentarily as it won't run the event handler on save. To fix this, I'm adding a new `ready` event in Talon v0.1.5 which will be called immediately (e.g. during script reload) if Talon was already `ready`.

improve Talon startup time

---

code/user_settings.py

This should fix #321 by automatically stripping whitespace from the "spoken form" in csv-based lists (currently vocabulary.csv & words_to_replace.csv).

strip whitespace from spoken form in csv-based lists

---

code/homophones.py

Currently phones appears to be using the longest word from the row. This seems sub-optimal since it's possible to order homophones.csv so that the most popular/common word is first
Separate PR coming in a few minutes with homophones.csv re-ordered with most popular word first.

Change phones so that first word is used instead of longest word

---

apps/mac/edit.talon

key(cmd-+) outputs command-shift-=, however macOS zoom is generally command-=.

macOS edit.zoom_in is incorrect (adds shift)

---

code/homophones.py
text/homophones_open.talon

I'm not sure if this is a problem that only affects me, but when using homophones and saying "pick", Talon (w2l, sconv-b6) often hears "pit" instead. This PR changes homophones to use "choose" instead of "pick". Open to other suggestions, or if nobody else has this problem I can just keep this a local change.

homophones: use "pick" instead of "choose" to avoid conflict with "pit"

---

apps/generic_browser.talon

This allows saying "go forward" (instead of just "forward") in generic_browser, for consistency with "go back" and "go home".
Also fixes a small bug, `back[ward]` (equivalent to `back | back ward`) instead of `(back | backward)`.
If nobody objects I'll just merge this by default in a few days.

generic_browser.talon: allow "go forward" for consistency with "go back"

---

modes/dictation_mode.talon

Sometimes you just need to press some keys in dictation mode. This makes that possible by adding an anchored "press" command:
```
^press <user.keys>$: key("{keys}")
```

add "press <user.keys>" for pressing keys in dictation mode

---

modes/dictation_mode.talon

I get tripped up by saying "clear left one word" instead of "clear left one words" in dictation mode reasonably often. This fixes that.
This PR allows nonsense like "clear left two word", but I think that's probably fine. You probably meant to say "words" anyway in that case, but got misheard :P.

dictation: allow "clear left one word" instead of "clear left one words", etc

---

modes/dictation_mode.talon

Enter is a fairly common english word, so I prefer "new line", although that is itself fairly common so other suggestions are appreciated. It's also more consistent with "new paragraph", which this adds.

dictation mode: replace "enter" w/ "new line", add "new paragraph"

---

text/generic_editor.talon

EDIT: PR now uses option (2), using *all* consistently.
I noticed that generic_editor was inconsistent between "select _all_", "copy _all_" vs "cut _everything_". This PR makes them all use "everything" for consistency (easier to memorise) and adds a "clear everything" command. I chose "everything" over "all" because `cut everything` and `clear everything` are slightly dangerous commands, and I figure "everything" is less likely to be accidentally recognized than "all". But I have no strong preference if folks prefer otherwise. Options:
1. Use 'everything' consistently: `select everything`, `copy everything`, `cut everything`, `clear everything`. 
2. Use 'all' consistently: `select all`, `copy all`, `cut all`, `clear all`.
3. Use `all|everything` for the common commands, `everything` for …

generic_editor.talon: use "all" consistently, add "clear all" command

---

apps/firefox/firefox.linux.talon
apps/firefox/firefox.mac.talon
apps/firefox/firefox.talon
apps/firefox/firefox.win.talon

This deduplicates a bunch of firefox stuff by having a non-operating-systems specific .talon file.

make firefox.talon file, move non-OS-specific stuff there

---

apps/vscode/vscode.py

After a recent updates, my visual studio code stopped being recognized. Meaning I only had access to the generic editor commands within my visual studio code.
This fixed my problem.
Ubuntu 20.04.1 LTS

FixVisualStudioCodeLinuxBug

---

apps/linux/terminal.talon
code/keys.py
misc/standard.talon

I think we're not supposed to be overriding voice commands based on context, but only actions. This makes "scroll up/down" run edit.page_up/down, and overrides this appropriately in linux terminals.
I thought about also changing "page up/down" for consistency, but this could make the actual page up/down keys inaccessible, which seems bad. Instead I added "page up" as a synonym for the "pageup" key, which should cover all previous uses of the command.

standard.talon: make "scroll up/down" use edit.page_up/down actions

---

code/keys.py

Fixes #351. I also made the "option" key name mac-specific, since I don't think other platforms call it that.

Make "command" and "option" keys mac-specific

---

code/dictation.py
code/vocabulary.py
modes/dictation_mode.talon
settings.talon

This implements context sensitive dictation, which determines how to space and capitalize dictated text by examining the text around the cursor before inserting.
I suggest reading this diff in the following order:
1. `modes/dictation_mode.talon`
2. `code/vocabulary.py`
3. `code/dictation.py`
4. `settings.talon`
The `word`, `text`, and `prose` captures got moved from vocabulary.py to dictation.py. This is because `text` & `prose` both need `format_text` and `prose` needs `auto_capitalize` and dictation needs `auto_capitalize`. We could split this by making something (eg. `auto_capitalize`) a talon action, but it seems like all this text-formatting code wants to be in the same place anyways. Open to other ways to organize this.
The capitalization code all became character based instead of …

Context sensitive dictation

---

apps/linux/gnome-terminal.talon

I'm not sure about enabling the user.git tag by default, but it seems to be what termite.talon does.

detect that gnome-terminal is a terminal on linux

---

code/code.py
lang/c/c.talon
lang/csharp/csharp.talon
lang/javascript/javascript.talon
lang/python/python.py
lang/python/python.talon
lang/typescript/typescript.talon

1. this allows each language to have their own default visibility for function declarations
2. this change overrides the default visibility for python to be public
the motivation for this change is twofold:
1. it's pretty rare to declare a function as private in python, so the default should be public (no underscore)
2. changing the underlying action instead of just the python.talon voice command keeps the implementation uniform across languages and makes overrides easy

implement user.code_default_function() for funky

---

code/search_engines.py
misc/search_engines.talon

Adds support for commands such as "google hunt hello world" to search for arbitrary text and "google this" to search for text currently selected by cursor.
Note: the specific search engines might not be generic enough?  For example I'm using Amazon Smile UK
Maybe should use a csv?

Add search engines

---

code/keys.py

The `keys` capture on line 102 and the `keys` dictionary on line 240
were being conflated, such that I could not use `key(escape)` in
a `.talon` file

Do not redefine the `keys` symbol

---

apps/i3wm/i3wm.talon

These settings are already present in the defaults defined
in the python file. Having them here as well makes it more
difficult to override them as a user.

Remove redundant settings for i3wm

---

apps/slack/slack.win.talon

offical documentation still states 'ctrl-j' but does not work on linux (v4.15.0) ¯\_(ツ)_/¯

updated unread shortcut

---

code/dictation.py

This improves dictation auto-spacing for quotation marks and currency symbols.
In particular, it means space will be added between inserted text and quotation marks if the quotation marks are already "attached" to some text, eg. inserting `they said` before `"John` will result in `they said "John` instead of `they said"John`.

Smarter auto spacing

---

lang/ruby/ruby.py
lang/ruby/ruby.talon

I know we're deprecating action() implementations in .talon files, but I'll let this stuff get changed along with the rest of the languages once we get the migrator.

Add basic definitions for ruby language

---

misc/repeater.talon

Add a "n times" repeater command that is easier to pronounce for most people and makes more sense naturally. It is also more consistent with the `repeat that` command.

Add repeater command that makes more sense (for newbies anyway)

---

apps/vscode/vscode.talon

See https://github.com/microsoft/vscode/issues/106535. Just started using VS Code and `workbench.panel.terminal.focus` is broken, it does not focus the terminal. The proper command is `workbench.action.terminal.focus`. The other commands with `panel` still work but may break in the future, too.

Fix broken "panel terminal" command for VS Code

---

apps/vscode/README.md
apps/vscode/command_client.py
apps/vscode/vscode.py

This PR switches to file-based RPC for the VSCode command server to improve security, and enables fallback commands using the command palette so that no extension is strictly necessary
Works with https://github.com/pokey/command-server/pull/3 on the VSCode side

Fix command server

---

text/generic_editor.talon

Likely more intuitive for beginners than `go way down`, `go way up`

Add 'go bottom', 'go top' commands

---

apps/generic_browser.talon

Adds a `go to <website>` command when we're in a browser. The difference from `open <website>` is that it only works if you've already got a browser focused and it visits the website in the current tab instead of opening a new one.

generic_browser.talon: add "go to <website>" command

---

code/code.py
lang/batch.talon
lang/c/c.py
lang/c/c.talon
lang/csharp/csharp.py
lang/csharp/csharp.talon
lang/go.talon
lang/java/java.talon
lang/javascript/javascript.talon
lang/python/python.py
lang/python/python.talon
lang/r/r.py
lang/r/r.talon
lang/ruby/ruby.py
lang/ruby/ruby.talon
lang/talon/talon.talon
lang/typescript/typescript.talon
lang/vimscript/vimscript.talon

Solves the problem that code.language doesn't update when forcing a language and until you change focus and the app title updates you have 2 language context active at the same time.
This is active if user.javascript OR code.language == javascript.
```
mode: user.javascript
mode: command
and code.language: javascript
```
Change it to this and the problem is solved sine auto_lang and user.javascript is mutex.
```
mode: user.javascript
mode: user.auto_lang
and code.language: javascript
```

Use auto_lang mode to detect if lang is forced or not

---

apps/vscode/command_client/command_client.py

Now that request file is removed talon-side, I believe this error message is no longer accurate

Tweak VSCode command_client error messages

---

code/screenshot.py
misc/screenshot.talon

* Remove app notification and instead use a brief white screen flash.
* By default store images in pictures folder instead of desktop. 
* Updated file name with application title when capturing a window to file. Makes it possible to categorize images later.
* On Linux use built in selection tool instead of third party utility. (Requires beta/v2 to get printscr button working).

Updated screenshot with flash and pictures directory 

---

code/code.py
code/screen.py
code/screenshot.py
code/window_snap.py
misc/screens.talon
misc/screenshot.talon

* Created screens module to have a unified ordering and management of screens
* Added command `screen numbers` to show screen numbering on each screen. 
* Added commands `grab screen <number_small>` and `grab screen <number_small> clip` to grab a specific screen by a number
- Issue #491
* Updated window_snap to use the same screen ordering

Added screens module and command to capture screen by number

---

code/keys.py

For English dialects that don't use the word 'quote' for the existing quote symbol

Add 'apostrophe' symbol

---

code/numbers.py

Fixes #478 by preventing a number_small from matching "ten" followed by a digit.

Fix #478, prevent "ten five" from being a number_small

---

apps/jetbrains/jetbrains.py

On my work station I use proxies, this gives me a 503 service unavailable when using Webstorm commands. Making sure that proxies are not used fixes the problem.

Jetbrains: Don't use proxies on request

---

lang/python/python.talon

add `state (try|except|raise)` to insert corresponding keyword, and `except {user.python_exception}` to insert "except {python_exception}:"

more python keyword commands

---

code/platforms/mac/edit.py

Fixes https://github.com/knausj85/knausj_talon/issues/499 by moving one character to the right before selecting the current word.
This handles both the edge case where you are on the left-most character of a word and where you are on the right-most character of a word

Fix 'select word' on mac

---

code/formatters.py
code/homophones.py

Added new actions to support homophones and reformat voice commands in cursorless.
`def reformat_text(text: str, formatters: str) -> str`
`def homophones_get(word: str) -> [str] or None:`

Added actions reformat_text and homophones_get needed by cursorless

---

code/switcher.py

Fixed function' new name update_running_list() instead of update_list()

Bugfix in switcher.py

---

.gitignore

As settings are now locally generated we should ignore the directory it creates

Ignore settings directory

---

apps/chrome/chrome.py
code/tabs.py
misc/tabs.talon

Fixes `tab close` command when repeating across a large number of tabs.
Relates to https://github.com/knausj85/knausj_talon/issues/454.
While this fixes this command for this issue specifically, I'm still supportive of a generic repeat delay framework rather than handling each case individually like this.
For those wondering why there is a wrapper: I had to add an extra layer of abstraction in order to not need to write the specific OS commands (cmd-w vs ctrl-w, etc) while rewriting the function.
https://user-images.githubusercontent.com/9077250/128190337-a8784b91-f11f-46ec-80f7-666415b0416a.mov

Add a small delay to tab close on Chrome

---

code/mouse.py
misc/mouse.talon

Adds a command to hold down right-click. This is useful for things like games where right click is used to pan the camera.
Some thoughts/design decisions here:
* the `mouse_drag` function was quite complicated since it had several responsibilities: starting drags and ending drags. Once you add a second type of drag this logic gets quite complex since the function now needs to start two types of drags, be able to end two types of drags and be able to switch between two types of drags in the case where one is enabled but not the one requested.
* In order to simplify it and keep functions as modular as possible, I moved ending drags into a separate function. Now `mouse_drag` is purely responsible for starting mouse drags. Drags can now be ended by calling `end drag` and with `touch`

Add right-drag command to Talon

---

text/symbols.talon

1. Adds a command to insert single quotes around text
2. Makes the command for single quotes and double quotes consistent with [keys.py](https://github.com/knausj85/knausj_talon/blob/master/code/keys.py#L159-L201)
3. Adds a 'string' option when making single quotes in order to be consistent with the 'string' command
Because this changes the behavior of the existing `quote that` and `inside quotes` commands, I'd love to get a few reviews and some discussion.

`quote that` and `inside quotes` changes

---

code/keys.py

This adds a symbol for the british currency, the pound sterling.
Relates to https://github.com/knausj85/knausj_talon/issues/512
This also sets us up as @rntz suggested to be able to use the term `{currency} sign` for various other currencies.
Since this removes one of the commands which creates a `#` symbol, I'd love to get multiple approvals and welcome any discussion.

Add Pound Sterling (£) Sign

---

apps/vscode/command_client/command_client.py

Avoids issues on Windows with non-US keyboard layouts with using alt key

Change command client keyboard shortcut

---

apps/kubectl/kubectl.talon
code/homophones.csv

This removes some of the warning spam caused by including characters other than a-z in the command graph. There are still some left in keys.py but I didn't touch those since I don't know whether or not dragon users need them.

Fix some warnings about unknown tokens

---

code/application_matches.py

Happy to adopt some other unique token other than 'VIM'.

Let windows with 'VIM' in title be recognized as vim.

---

code/platforms/linux/edit.py
code/platforms/mac/edit.py
code/platforms/win/edit.py

Fixes the select word edge case [here](https://github.com/knausj85/knausj_talon/issues/526).
The edge case involves having the cursor just before the very first character of the word and the `select word` command selecting the word before the current word.
It would be great if any windows or linux users could give this a quick test since I'm not able to run it.

Fix select word on Windows and Linux

---

apps/evernote/evernote.talon
apps/evernote/mac.talon

There are a couple of things I'd like to add to this module eventually, but the main pain point of using Talon with Evernote is that it's a text editor but `slap` often gets jumbled. Adding the key delay fixes that. Hopefully this helps others.
I played around with different delays for a while to try to find one that made slap always work while introducing minimal delay. If anyone else ends up having issues with this though, we can always increase it later on.
Note that this is an issue that I have on Evernote for Mac. In the past I found the Windows app to be much faster and we may end up wanting to split this into a Mac-only delay.

Add Evernote module to Talon

---

code/homophones.py

There is an edge case in https://github.com/knausj85/knausj_talon/issues/501 where homophones picked from the GUI always became lower case no matter what the case of the original word was.
**Example of new case matching when picking from the GUI**
**In terms of integration with Talon formatters:**
I spent a bit of time working on making this work with formatters from format.py, but ultimately decided that it was unnecessary since the basic `capitalise` and `upper` formatters cover most (all?) `phones` use cases for now. It shouldn't be very hard to extend to use the Talon formatters later if we ever see a need.

Make sure homophones always retain case

---

code/homophones.py

Example:
The homophones window currently shows the word that is selected (and in a random position in the list) which increases the cognitive load when trying to find the option you want. This PR filters it out as an option.

Hide the selected word from the list of homophone options

---

code/switcher.py
misc/window_management.talon

DONOTMERGE - Only works on Windows currently.
Throwing my 2c into the ring on this cause I needed it locally. The problem is that it's challenging to switch between two windows with the same name (e.g. two instances of chrome with different tabs, or two instances of vscode with different repos open). This merely opens up the same `alt-tab` menu and let's you choose with your voice.
I would LOVE to get this working on mac, but I couldn't figure out how. I'm not sure what the equivalent for linux would be.
See also: https://github.com/knausj85/knausj_talon/pull/73 https://github.com/knausj85/knausj_talon/issues/373

switcher menu

---

code/dictation.py

Context-sensitive dictation peeks left and right to get context for spacing and capitalizing inserted text. Depending upon the text inserted, this context may not be necessary. This PR avoids looking for context on the left if there is no circumstance where we need to insert space on the left or add capitalization.

Optimise context-sensitive dictation to avoid peeking left if unnecessary

---

code/platforms/mac/app.py

`cmd-alt-right` and `cmd-alt-left` work to switch tabs in Firefox and Chrome on MacOS, but not in Safari or Finder.
The 'native' keyboard shortcut for stepping through tabs on MacOS is Control-Tab or Shift-Command-] (for next) and Control-Shift-Tab or Shift-Command -[ (for previous). See the [Safari](https://support.apple.com/en-gb/guide/safari/cpsh003/mac#ibrwc08c3c09) and [MacOS](https://support.apple.com/guide/mac-help/use-tabs-in-windows-mchla4695cce/mac#mchl7799ee89) docs.
Thankfully, the 'native' shortcuts work in Chrome and Firefox as well (in addition to Safari, Finder, etc)

fix tab_next and tab_right shortcuts for MacOS

---

apps/slack/slack_mac.talon

cmd-j doesn't seem to do anything, and I presume this is meant to jump to "all unreads" like I think the Windows/Linux one does?
https://github.com/knausj85/knausj_talon/blob/4ac7ba1f6b72f79d6e463b88a288f553627ae446/apps/slack/slack_win.talon#L24

Fix macOS Slack unread command

---

apps/platforms/win/wsl/wsl.py
code/file_manager.py

The first commit here is a simple optimization.
The second commit exposes error messages that may be generated during wsl path detection and which were previously hidden. Part of the code was refactored in order to provide for common error handling. There is code to detect and decode a class of errors formatted in utf-16-le which may be generated by the wsl engine itself (rather than the guest distros).
This change is the first of several for this module which I would like to contribute.  Primary goals include cleanly supporting multiple distros and integration with the broader terminal/Linux framework present in knausj_talon. In the long run, it would be nice to refactor this code into a more OO implementation.

Improve WSL error logging

---

apps/evernote/mac.talon

Because on odd occasions commands still get jumbled

Increase the Mac Evernote app delay slightly

---

README.md
mouse_grid/mouse_grid.py
mouse_grid/mouse_grid.talon
mouse_grid/mouse_grid_always.talon
settings.talon

the tag for activating "m grid" proved to be a very bad idea.

deprecate "m grid" for "mouse grid" forget tag

---

lang/talon/talon.talon

See https://github.com/knausj85/knausj_talon/issues/600.

Restore basic actions list when dictating TalonScript.

---

lang/python/python.py

This changes `state switch` and `state case` to insert the keywords for [PEP 634: Structural Pattern Matching](https://docs.python.org/3/whatsnew/3.10.html#pep-634-structural-pattern-matching), added in Python 3.10.

python: Add match statement support

---

apps/chrome/chrome.py
apps/chrome/mac.py
apps/platforms/mac/sarafi/safari.py

Use accessibility where possible, otherwise AppleScript (which would generate an additional permission prompt the first time).  On Safari use the address bar (if it's visible); on Chrome use the first AXWebArea.

Browser address implementations for Safari and Google Chrome on Mac.

---

apps/web/window_titles.md

The [previously suggested Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/domain-in-title/) only appends `[hostname]` to the tab title. However, `code/browser.py` in #631 requires both the scheme and host to be present.
This replaces that suggestion with [a Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/keepass-helper-url-in-title/) that prepends the URL to the window title (not the tab title) and adds some guidance on how to configure it to work with these scripts.

web: Explain what to configure in window titles

---

code/mouse.py

Currently the initial speed of the continuous scroll can be increased if you do any manual "wheel up/down" actions.
For example call "wheel down 20 times" and then start "wheel downer". It will go a lot faster. 
This change should fix that. This change is consistent with the code for starting the gaze scroll.

Fix issue with initial continuous scroll speed

---

apps/vscode/command_client/command_client.py

Until we figure out what's wrong with high function keys on ubuntu and vscode, we can just use the old command server shortcut

Work around Linux f17 issue

---

code/create_spoken_forms.py

temporary fix for the error mentioned in #658, eliminates the use of type variables in create_spoken_forms.py and replaces them with Any

create_spoken_forms.py: use Any instead of T

---

code/numbers.py

fixes #634, so bare "hundred" "thousand" "million" etc will no longer recognize as numbers.
also disallows leading "oh" in number words, in particular preventing bare "oh" from recognizing as 0. I could factor this into a separate PR if desired, but it seems to be a common pain point.
In my testing this seems to perform fine during DFA compilation and command parsing. Would appreciate further testing.

numbers.py: disallow leading scale words

---

code/phrase_history.py

Currently we use `edit.delete()`, but `edit.delete` is supposed to be for deleting the current selection, not deleting the character before the cursor. That's what backspace does.

use "backspace" for deleting last phrase

---

lang/talon/talon.py

In talon.py, update_lists has a confusing name, since `'update_lists'` is in fact the name of a different callback we can register for; this PR renames it to be called `on_update_decls`, since that's when it's called.

talon.py: rename update_lists to on_update_decls

---

text/line_commands.talon

camel_left/right functions were only in the line_commands.py python file. adding it also to the talon file

adding missing camel_left/right to the line_commands.talon

---

.gitignore
apps/vscode/command_client/command_client.py

Touches a file known to the VSCode command server before executing any phrase, to allow VSCode extensions to detect start of phrase and maintain consistency over the course of a phrase.
Inaugural use case is allowing cursorless to freeze a snapshot of the hats so that they don't shift over the course of a single command phrase (https://github.com/pokey/cursorless-vscode/pull/318)

Command client pre-phrase signal

---

draft_editor/draft_editor.py
draft_editor/draft_editor.talon
draft_editor/draft_editor_open.talon

Switches to using tags for everything and then setting them by listening for app focus switch rather than trying to use `matches`.  Should be more robust, and also means it should reflect settings changes in real time
Also fixed timing issue on submit

Fix VSCode draft window on Mac

---

apps/adobe/adobe_acrobat_reader_dc.py
apps/adobe/adobe_acrobat_reader_dc.talon
apps/adobe/win.py
apps/calibre/calibre.py
apps/calibre/calibre_viewer.py
apps/calibre/calibre_viewer.talon
apps/kindle/kindle.py
apps/kindle/kindle.talon
apps/kindle/win.py
apps/okular/okular.py
apps/okular/okular.talon
apps/platforms/linux/atril/atril.py
apps/platforms/linux/atril/atril.talon
apps/platforms/linux/evince/evince.py
apps/platforms/linux/evince/evince.talon
apps/platforms/win/nitro_reader/nitro_reader_5.py
apps/platforms/win/nitro_reader/nitro_reader_5.talon
apps/platforms/win/sumatrapdf/sumatrapdf.py
apps/platforms/win/sumatrapdf/sumatrapdf.talon
code/chapters.py
code/pages.py
misc/chapters.talon
misc/pages.talon

Add tags to navigate pages and chapters.
Implement pages (and chapters/tabs when applicable) for reader apps:
- Adobe Acrobat Reader DC (mac missing)
- Calibre Viewer (mac missing)
- Kindle (mac missing)
- Okular (mac missing)
- Atril
- Evince
- Nitro Reader 5
- Sumatra PDF
Since I don't have a Mac, I could only implement for Windows and Linux.

Add page navigation for reader apps

---

apps/chrome/chrome.py
apps/chrome/linux.py

This lets Chrome/Chromium on Linux benefit from the generic browser commands. This PR also improves the reliability of the recently merged tab duplicate command (cc @xavier630).

Add browser action implementations for Chrome on Linux

---

modes/dictation_mode.talon

I was a bit confused by this initially, because I thought it was saying that every insertion (including string literals) should be wrapped with `auto_insert()`.
But it's really just saying that you should call `auto_insert()` over `insert()` to ensure the text goes through the dictation inserter override defined here:
```python
@dictation_ctx.action_class("main")
class main_action:
def auto_insert(text): actions.user.dictation_insert(text)
```

dictation_mode: clarify comment

---

apps/chrome/chrome.py

I've also removed a redundant match for `app.name: Google Chrome` in the windows block, since we already match that on any OS.

recognize google chrome on ubuntu

---

code/dictation.py

Goals of this PR:
1. Make it easier to change what "modifiers" are available in prose/dictation. Currently the meanings of "caps", "no caps", "no space" are hardcoded into `apply_formatting`, which must be kept in sync with both the `prose_modifiers` list and `dictation_mode.talon` commands.
2. Reduce duplication between prose_modifiers and dictation_mode.talon.
3. Allow curly quotes to be used without being auto-straightened, while still getting spacing right for open/close quote commands.
Progress:
- Made a global dictionary, `prose_modifiers`, that maps modifier names to DictationFormat methods; used to generate `{user.prose_modifiers}` and in `apply_formatting`. So instead of editing three places (dictation_mode.talon, the prose_modifiers list, and apply_formatters) you only need to …

dictation.py refactoring

---

lang/javascript/javascript.talon

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

javascript: Add 'state export'

---

apps/jetbrains/jetbrains.py

IntelliJ allows for having projects with multiple modules, in a similar manner to multiple folders in a VSCode workspace.
This ignores the module name in the title, shown in square brackets after the filename.
I believe this fixes the issue described by @Michaelt293 in #408.

jetbrains: Ignore project module names

---

lang/c/c.py
lang/c/c.talon
lang/csharp/csharp.talon
lang/java/java.py
lang/java/java.talon
lang/javascript/javascript.talon
lang/tags/comment_block.py

In #656 the block comment actions were renamed for consistency, however their implementations were not renamed. The only implementations of these were for C and Java.
This adds a common implementation for C-style block comments behind a tag, and adds the tag to C# and JavaScript.
Using a tag makes it easier for users to override `code_comment_block` for their editor (targeting the relevant languages) if needed (for example, if their editor auto-closes block comments).
This assumes that #716 will be merged, and hence does not add the tag to typescript.talon.

Add tag for C-style block comments

---

code/dictation.py

Currently context-sensitive dictation peeks left for context before it inserts and peeks right after it inserts to determine whether to add a trailing space. This has the unfortunate effect in some editors (eg. emacs) of separating the insertion from the trailing space in the undo-chain, so you have to undo twice: once to eliminate the trailing space, once to undo the insertion. This PR fixes this by doing all peeking before insertion. However, it has the unfortunate side-effect of making context-sensitive dictation feel slower, because we have to do more work before we can start inserting text. Suggestions welcome.

dictation.py: do peek_right before insertion to not break undo chain

---

apps/vscode/vscode.py

VSCode's default keybindings for "switch to tab N" conflict with the default-ish macOS "switch to desktop N" keyboard shortcuts. This uses the command client to execute the desired commands instead.
I wasn't able to use the `openEditorAtIndex` via the command palette, so I'm being conservative and only doing this for macOS.

vscode: Fix go tab conflict with Mac desktop keys

---

README.md

Update the README to use consistent ordering of the 'help' commands, i.e.
change 'format help' to 'help format'. While both versions are supported, seems
preferable to be consistent with the other 'help commands'.

prefer consistent ordering of 'help' commands in README

---

code/formatters.py

currently if the user has a word that is capitalized in the lexicon, eg. "Baltics", then it'll be capitalized by "camel": "camel baltics hello" -> "BalticsHello". This is probably undesirable; this PR fixes it.

lowercase first word in camel-case formatters

---

apps/chrome/chrome.py

Windows already works (the downloads I've found use chrome.exe) and Linux already has a custom matcher for Chromium

Link Mac Chromium to Chrome config

---

lang/c/c.py
lang/c/c.talon

This common types dictionary was created but unused before. I've renamed it to c_keywords as that more accurately describes what was inside the dictionary (though it is not a complete list of the c keywords at the moment) .  I've then tried to plug it into the .talon file the same way the c_types dictionary is.

Add c keywords

---

apps/platforms/mac/safari/safari.py

This sometimes inadvertently scanned in the web page. Now we only look in the window's toolbar for the address and search field.
Tested in all toolbar configurations in macOS 10.15 and 12.
Also add a short timeout to attempt to prevent hangs while trying to retrieve the frontmost tab's URL via AppleScript (backup method).

Fix watchdogs when getting page address in Safari

---

code/keys.py
misc/keys.talon
modes/dictation_mode.talon

Fix #713 and #741:
- `go <user.arrow_keys>` now invokes `edit.left/right/up/down`.
- `press` now has two forms, `press <user.keys>` to press a sequence of keys (eg. `press left left up`) or `press <user.modifiers>` to press a modifier key-combo (eg. `press control super`). These are present in command mode and (anchored) in dictation mode.

make "go <arrows>" use edit.left, allow "press <keys>" for arrow keys instead

---

lang/java/java.py
lang/java/java.talon

While submitting a pull request for terraform (#752), I got some valuable feedback on how to write language files. It turns out I made some mistakes because I copied a lot from the java definition files. This pull request aims to fix the following deviations:
- use singular for lists
- use `insert` instead of `auto_insert`
- restrict to command mode
Also, I removed an apparently unused function (`user.java_access_modifiers` appears to be undefined).

Align java with other languages

---

apps/terraform/terraform.py
apps/terraform/terraform.talon
code/code.py
lang/terraform/terraform.py
lang/terraform/terraform.talon
modes/language_modes.talon

This merge request intends to add support for [terraform](https://www.terraform.io/). Since terraform is both an application and a language, I included basic bindings for both.
Terraform uses a declarative language, so I could not implement most of the mutating definitions in tag `user.code_operators_assignment`. I included this tag only for the assignment operator. I'm not sure of this is the right way to go.

Add support for terraform

---

code/user_settings.py

See footnote: https://docs.python.org/3/library/csv.html#id3
I can confirm that I witnessed this bug and this fixes it.

Fix duplicate newlines in CSVs on Windows.

---

code/history.py

Fixes #757
Fixes #660
Also adds support for user-defined history phrase transformation by overriding `user.history_transform_phrase_text` action
This PR starts to move us in a direction where users have more flexibility to influence knausj behaviour without needing to have a fork, by adding an action that the user can override
Here's an [example](https://github.com/pokey/pokey_talon/blob/main/custom/code/history.py) of user-defined history processing

Improve phrase history mechanism

---

code/vocabulary.py

Partially fixes #760; removes everything except month names, since we don't need them anymore with conformer's lexicon. I haven't tested this on public, though. Can someone double check that the words I removed are capitalized properly on public when removed from words_to_replace.csv?

simplify _capitalize_defaults

---

code/screenshot.py

Remove redundant `ctrl` press from Mac screenshots

Remove redundant `ctrl` press from Mac screenshots

---

code/dictation.py
tests/test_dictation.py

This works out of the box in Dragon. To test in Conformer you'll need to add something like this to additional_words.csv:
```
i.e.,I E
e.g.,E G
```

Handle capitalization of e.g. and i.e. within prose.

---

apps/vscode/snippets/csharp_snippets.py
apps/vscode/snippets/python_snippets.py
code/code.py
lang/batch/batch.py
lang/batch/batch.talon
lang/c/c.py
lang/c/c.talon
lang/csharp/csharp.py
lang/csharp/csharp.talon
lang/go/go.talon
lang/java/java.py
lang/java/java.talon
lang/javascript/javascript.py
lang/javascript/javascriptreact.talon
lang/markdown/markdown.talon
lang/python/python.py
lang/python/python.talon
lang/r/r.py
lang/r/r.talon
lang/ruby/ruby.py
lang/ruby/ruby.talon
lang/talon/talon.py
lang/talon/talon.talon
lang/terraform/terraform.py
lang/terraform/terraform.talon
lang/typescript/typescript.py
lang/typescript/typescript.talon
lang/typescript/typescriptreact.talon
lang/vimscript/vimscript.py
lang/vimscript/vimscript.talon

Instead of the following header
```
mode: command
and mode: user.c
mode: command
and mode: user.auto_lang
and code.language: c
```
We can now just use
```
tag: user.c
```
Also took the liberty to add a few new file endings when I was in there.
@rntz @knausj85 @pokey 
Would probably be nice to get this one merged before the other pr regarding new languages

Updated language context to use tags instead of modes 

---

code/screenshot.py
misc/screenshot.talon

This is an important UI on mac for taking screenshots as it's where you decide where to save it, whether it will be a video, if a timer should be used, etc.
I'm open to ideas for the command naming, the naming I went for matches the pattern in the file but could be more intuitive.

Add command to open screenshot settings

---

apps/terraform/terraform.py
apps/terraform/terraform.talon

#776 introduced a bug if the user explicitly set the tag `user.terraform`, which already existed due to #752. Terraform is both an application and a language, which is why this collision occurred. The bug manifested in lang/terraform/terraform.py
always being evaluated if a user explicitly set the client tag. This PR renames the client tag to fix this.

Fix terraform client tagging

---

apps/platforms/linux/terminator/terminator-linux.py

Added terminator for Linux, based on the gnome terminal.
Shortcuts appropriately updated, and split window functionality implemented based on the splits tag.

Terminator for Linux

---

apps/vscode/vscode.py

A newly downloaded version of VS Code - Insiders has a dash in the name now 🤷 Before I added this line Talon wasn't recognizing the Insiders version at all.

Add new name variant for VS Code - Insiders

---

apps/gdb/gdb.py
apps/kubectl/kubectl.talon
apps/windbg/windbg.py
apps/windbg/windbg.talon
code/dictation.py
code/insert_between.py
lang/c/c.talon
lang/csharp/csharp.py
lang/go/go.talon
lang/java/java.py
lang/java/java.talon
lang/javascript/javascript.py
lang/javascript/javascript.talon
lang/python/python.py
lang/python/python.talon
lang/r/r.py
lang/talon/talon.talon
lang/terraform/terraform.py

Fixes a few things:
1. insert_cursor was in `lang/python/python.py`, which is a weird place. This moves it to `code/insert_between.py`.
2. insert_cursor looks for a magic symbol, `[|]`, to determine where to put the cursor. This is fine for inserting constant strings but means we can't use it more widely. I've replaced it with `insert_between(before, after)`, which takes two strings and doesn't look for magic symbols.
3. Updated lots of code to use insert_between instead of manually calling edit.left() after inserting stuff.
One of the nice things about `insert_between` is that it might eventually be possible to implement it more efficiently (eg via accessibility APIs), avoiding the repeated edit.left()s.

replace insert_cursor with insert_between

---

misc/talon_helpers.talon

Added two commands that print out urls to the Talon and Knausj
issue trackers to encourage bug reporting.  Right now the link to
the Talon issue tracker is hidden as a pinned message on the help
channel of the slack.  Attaching it to the command 'report Talon bug'
may make it easier to find.

voice commands for reporting bugs

---

lang/scala/scala.py
lang/scala/scala.talon

This pull request intends to extend the scala language definitions introduced in #735. If applied, it will
- add further types
- add modifiers
- add keywords
- remove added `enter` after `else` keyword to enable `if(foo) bar else baz` syntax

Extend Scala language

---

code/websites_and_search_engines.py

To lower the activation energy for people to be able to get to the websites where you can find help, I added 
"talon website":"http://talonvoice.com",
"talon slack":"http://talonvoice.slack.com/messages/help",
"talon wiki":"https://talon.wiki/",
"talon practice":"https://chaosparrot.github.io/talon_practice/",
"talon repository search": "https://search.talonvoice.com/search/",
As defaults to website.csv, so that the command 
*open talon website*  launches the talon website
*open talon slack* launches the talon slack  and puts you in the help channel by default
*open talon wiki* launches the talon wiki
*open talon practice* goes to chaosparrot's talon practice website.

Tara Added talon resource websites as defaults to websites.csv

---

code/platforms/linux/edit.py
code/platforms/mac/edit.py
code/platforms/win/edit.py

edit.select_line(n) takes an argument saying what line to select, or `None` for current line. Currently the default implementations unconditionally select the current line. This fixes that.

fix select_line default impls to go to the given line

---

README.md
apps/generic_snippets/generic_snippets.py
lang/c/c.py
lang/c/c.talon
lang/csharp/csharp.py
lang/csharp/csharp.talon
lang/java/java.py
lang/java/java.talon
lang/javascript/javascript.py
lang/javascript/javascript.talon
lang/python/python.py
lang/python/python.talon
lang/r/r.py
lang/r/r.talon
lang/rust/rust.py
lang/rust/rust.talon
lang/tags/functions_common.py
lang/tags/functions_common.talon
lang/tags/functions_common_gui_active.talon
lang/talon/talon.py
lang/talon/talon.talon
lang/typescript/typescript.py

Fixes #732
This commit refactors the misleadingly named functions_gui tag and the associated list, tags, and files, as @pokey suggested in #732. 
It also removes dead configuration for some languages.
As suggested in the issue, I changed the name of the function list to singular to increase readability and align with the code standard. I deviated from pokey's suggestions in that I used the tag `code_functions_common` instead of `code_common_functions` (same with the file names). I did so to conform with the pattern established by other tags e.g. `code_operators_array` or `code_data_bool`.
I was as careful as possible, but considering the large number of files I had to touch, this pull request has the potential of breaking functionality. Therefore, I would welcome a thorough review. I …

Refactor functions_gui to functions_common

---

apps/brave/brave.py
apps/brave/mac.py
apps/web/window_titles.md

EDIT: This adds Brave as a new browser application. See below for the original issue description.
----
Brave is a web browser built on Chromium and so I thought it was fitting to add it as a variant of Chrome.
This is my first contribution and I'm still getting used to what the configuration parameters are used for if I haven't got it right please correct me. I see this in the contributing section in the README
>For Mac OS X, the bundle id should be used for defining app contexts, rather than the name
And I'm not sure if I've done more than I should have there.
Also I don't have access to a Windows machine (only mac) to test but some googling suggested what the .exe name would be.

Add Brave as a new browser applicatoin

---

code/user_settings.py
code/vocabulary.py
misc/vocabulary.talon

Implements Option 1 in #792.
See also https://github.com/wolfmanstout/talon-vocabulary-editor/blob/main/vocabulary.py for a fancier version of this that depends on unstable APIs (for parse_phrase.py). That is intended to override this simpler implementation. There is some duplication of code, unfortunately, but I think that would be hard to avoid without exposing a bunch of functions as actions that don't need to be otherwise (i.e. the CSV functions). Open to feedback, though!

Added commands for adding vocabulary words/phrases

---

lang/c/c.py
lang/rust/rust.py

I'm adding a DeprecationWarning to Talon when you don't put a space between distinct words in grammar rules, e.g.
```python
2022-05-10 14:50:04 DEBUG [+] /Users/aegis/.talon/user/knausj_talon/lang/c/c.py
2022-05-10 14:50:04 DEBUG DeprecationWarning: Rule needs a space between tokens:
[<self.c_signed>]<self.c_types> [<self.c_pointers>+]
^^
2022-05-10 14:50:04 DEBUG DeprecationWarning: Rule needs a space between tokens:
[<self.stdint_signed>]<self.stdint_types> [<self.c_pointers>+]
^^
2022-05-10 14:50:04 DEBUG DeprecationWarning: Rule needs a space between tokens:
[<self.c_signed>]<self.c_types>[<self.c_pointers>]
^^            ^^
```
This commit fixes all cases of the warning in upstream knausj_talon. Note that I removed some incorrect comments about the spacing in lang/c in the process. …

add space between grammar rule words

---

code/code.py

For some reason in bcb318c PHP was removed from the languages list even though it has full support, so I'm adding it back in.

Add PHP back to code/code.py

---

code/formatters.py

addresses part of #851. doesn't change "all caps" to "all cap" because I'm less convinced that won't screw up recognition for people who are used to "all caps", needs testing. I'm gonna merge this the next time I get around to it if nobody objects, we can always go  "all caps" -> "all cap" later.

formatters.py: put spaces in "all down", "all caps"

---

code/formatters.py

Currently, we can't unformat snake case.  For example, selecting `hello_world` and saying "camel that" won't do anything
Thanks to @AndreasArvidsson for the pairing session to fix

Fix unformat text for snake case

---

code/homophones.py

Before this change, if homophone sets in the CSV contained overlapping words, they would be merged, but only the last set of homophones would be updated with the merged set. This fixes it so that all homophones point to a consistent set.

Fixed merging of homophone sets when loading CSV.

---

code/mouse.py

Updating the behavior of the action to match the original `toggle_control` function, which allows passing a bool to enable or disable the control mouse mode. I want to enable and disable the control mouse mode via hotkeys specified in a talon file. This allows a hot key to have a consistent behavior regardless of whether the mode was initially enabled or disabled. If no bool is passed in, it maintains the current behavior of flipping the current mode.

Add action to enable/disable control mouse explicitly

---

apps/i3wm/i3wm.talon

When using `i3-msg workspace $NUM` we will create the workspace if it
does not exist.
If we have a numbered workspace, with a custom name as per the
documentation:
https://i3wm.org/docs/userguide.html#_named_workspaces
Then we will create a _new_ workspace with a name of `$NUM` and number
`$NUM`
See these commands:
```
> i3-msg -t get_workspaces | jq ".[] | select(.num == 1)"
{
"id": 94184672696560,
"num": 1,
"name": "1: 1 - work",
"visible": true,
"focused": true,
"rect": {
"x": 1920,
"y": 24,
"width": 3840,
"height": 2136
},
"output": "DP-1-4",
"urgent": false
}
```
then run the command as it _was_ for the utility
```
> i3-msg workspace 1
[{"success":true}]
```
and compare the output again
```
> i3-msg -t get_workspaces | jq ".[] | select(.num == 1)"
Start 15:19:11
{
"id": …
```

Force navigation to i3wm numbered workspace by number, not name

---

lang/javascript/javascript.py
lang/javascript/javascript.talon
lang/python/python.py
lang/python/python.talon
lang/tags/keywords.py
lang/tags/keywords.talon

Fixes #807
Adds support for keywords, such as "return", "export", etc.  Note that these differ from the usual "state" commands (eg "state if"), because they insert only the keyword, rather than building the statement, which would include adding parentheses, etc
They can be chained, so you can say eg "keyword return false"
Note that there is definitely some overlap with many of the "state" commands; might be worth thinking whether that is a problem
We may want to consider removing a few of the JS "state" commands that are just keywords https://github.com/knausj85/knausj_talon/blob/796bb9ec84e7e897f1fde141ee664b944e303a1e/lang/javascript/javascript.talon#L31-L41

Add support for programming language keywords

---

talon_draft_window/draft_window.talon

For anyone familiar with cursorless these may be baked into their memory. I learned cursorless before I used the draft window and saw the commands could be fairly easily expanded to allow for the cursorless style phrasing. Obviously this is only snapshot in time and cursorless could evolve in future but perhaps this small selection will always be compatible.
Interested to know if folks think this is an appropriate addition or not.
I can also make a small addition to the draft_window README mentioning cursorless compatibility if this is desired.

Add equivalent cursorless commands as options for the draft_window

---

lang/c/c.talon
lang/javascript/javascript.py
lang/tags/functions.py
lang/tags/functions.talon
lang/typescript/typescript.py
tests/stubs/talon/__init__.py
tests/test_code_modified_function.py
tests/test_formatters.py

Adds the following:
* Allow flexible combination of function modifiers (static, public etc.) in funky command. Allows for easier addition of 'non standard' modifiers (e.g. async in javascript), and suppression of irrelevant ones (e.g. static in javascript).
* Adds the 'private' modifier and makes the unadorned 'funky' in Typescript emit an unmodified function.
* Updates the test stubs so that the @mod.action_class decorator registers actions in a similar way to Talon.
Addresses #825 and replaces #824 .

Flexible funky modifiers

---

code/abbreviate.py
code/edit_text_file.py
code/open_file.py
misc/edit_settings.talon

Changes:
1. Adds a new `user.open_file` action which opens a file in whatever the appropriate application is.
2. Adds a list `user.talon_settings_csv` for paths to talon user settings csv files, e.g. additional_words.csv, search_engines.csv, etc.
3. Adds a command `customize {user.talon_settings_csv)` that opens the corresponding csv and jumps to end of file.
This is heavily based on #810.
Feedback requested:
1. Is `customize` the command prefix we want here? At present this will bind the ccommands:
```
customize search engines
customize websites
customize file extensions
customize system paths
customize words to replace
customize additional words
```
Alternatives might be `edit` or `open` (a bit short), `add new`, `edit talon`, `edit {talon_settings_csv} csv`.
2. Is there a better place …

add user.open_file action and list/commands for editing settings csvs

---

.github/workflows/ci.yml

This fixes the GitHub Actions CI workflow to run after the `master` branch was renamed to `main`.

ci: Fix after main branch migration

---

lang/batch/batch.py
lang/java/java.py

These tags aren't defined anymore; let's remove them to reduce confusion.
There was a little bit of discussion about this on https://github.com/knausj85/knausj_talon/pull/743, although they still made it in.

batch, java: remove references to obsolete tags

---

apps/discord/discord.py
apps/slack/slack.py

This adds support for the Discord and Slack webapps.
Some of the keyboard shortcuts conflict with browser shortcuts, but this may vary from browser to browser, so I figured leaving them as is for now is probably fine, e.g. <kbd>cmd-k</kbd> to open the Slack channel picker on macOS conflicts with Firefox's focus search bar shortcut.

Support Discord and Slack in browser

---

text/text_navigation.talon

I spent my morning trying to understand why the `text_navigation` module worked in notepad but not VSCode.
Turns out that VSCode has a setting `editor.emptySelectionClipboard` where if your cursor has nothing selected you'll select the whole line instead, which leads `navigate_right` and `navigate_left` actions to fail.
I've been wanting to use these commands for a long time but it kept going into the too hard basket.
Hope this comment might help someone else.

Add vscode settings comment for text navigation

---

misc/mouse.talon

This adds spaces in the middle of the `mid click`, `dub click`, and `trip click` commands to improve recognition. 
(I've always had issues with the `dub-` commands myself without a space.)

mouse: Use real words in click phrases

---

code/dictation.py

Fixes bug with dictation dance in VSCode where empty selection caused copy to get whole line and mess things up
Note: implemented in pairing session with @rntz

Fix dictation dance in vscode

---

code/create_spoken_forms.py
code/help.py
code/numbers.py
code/vocabulary.py
lang/tags/operators_assignment.py
lang/tags/operators_assignment.talon

#920 
This should make it so that the bitwise assignment operators are now able to be used.

#920 Inconsistent function names/descriptions in operators_assignment.py and operators_assignment.talon

---

.pre-commit-config.yaml

We don't want pyupgrade: https://github.com/knausj85/knausj_talon/issues/922
We will add back individual formatters later.

pre-commit: removed shed

---

.pre-commit-config.yaml

#925
This re-adds:
- the Black code formatter
- the isort import sorter
These provide most of the value we were getting from Shed and are probably the safest of what Shed was running. There are no changes to the codebase after running them.
If you want a more incremental change, just take the first commit, which adds only Black.

pre-commit-config: re-add Black and isort

---

lang/rust/rust.py

This applies the Black formatting changes to all files, which picks up changes in between the removal of the formatter in #923 and its reintroduction in #926, which was just one change to rust.py.

all: formatting changes

---

code/edit.py

Squashes some warnings from talon. My only concern here is that this API may not yet be in public talon. Can someone check?

selected_text(): use capture().text() not .get()

---

code/dictation.py
talon_draft_window/draft_talon_helpers.py

I optimized the fixes made in #902 to involve fewer keypresses, which will help when these are expensive (eg. on Linux :P). Mainly:
1. I removed the clobber argument to dictation_peek_left, we only ever call it with clobber=True and inserting space will already clobber the selection, so this gets rid of a space-backspace pair.
2. I used edit.extend_line_end in dictation_peek_right instead of edit.extend_right multiple times.

faster dictation dance

---

.editorconfig

As evidenced in #947 the majority of our .talon files use 4-space indents. This changes the default to 4 spaces, overriding it for Markdown and YAML files (which should always be 2 spaces).

editorconfig: Default to 4 spaces

---

apps/vscode/vscode.py

This allows jumping to tabs 10 onwards with `go tab ten` and so on.

vscode: Implement jumping to tab 10+

---

code/keys.py

Use `"coma"` for `,` to work around conformer b-series issue

---

lang/java/java.talon

This adds a convenient way to insert the Java 10+ keyword for local variable type inference, as in:
```java
var url = new URL("http://example.com/");
```

java: Add `state var`

---

.pre-commit-config.yaml

Fixes:
- Support for negative numbers
<https://github.com/wenkokke/talonfmt/issues/17>
- Support for settings with preceding underscores
<https://github.com/wenkokke/talonfmt/issues/16>
- Support for key bindings
<https://github.com/wenkokke/talonfmt/issues/8>

Bump talonfmt version

---

lang/tags/operators_assignment.talon

As far as I can tell, these actions were never given spoken forms. I am not sure if there is a reason for this, so I wanted to add some in case it was an error.
I made "wise" optional in the command so it does not get too long, but the square brackets can be removed if that does not seem necessary. If this is useful in reducing command length, maybe similar commands could be formatted to make the "wise" in "bitwise" optional.

Add spoken commands for bitwise and/or assignment

---

lang/c/c.py
lang/rust/rust.py

Apologies, I accidentally closed the first pull request for this.
When these insert library functions were called in their respective talon files, the first argument was the name of the library, and the second argument was an empty string. As a result, it was pasting an empty string ("selection") instead of the library name ("text").
Also, one of the capture rules for c didn't match the name used for it in the associated talon file, causing the voice commands to not work.

Bugfixes for c, rust

---

lang/c/c.talon

In C mode, makes it quicker to use `#define/undef/ifdef` by adding commands `[state] define <user.text>$` etc. eg: `define hello world` -> `#define HELLO_WORLD`.

c.talon: allow text after #define/undef/ifdef

---

core/tags.py

The `debugger` tag is already defined in `tags/debugger/`:
https://github.com/knausj85/knausj_talon/blob/0d6bd90e5bb1a45b5cea7bcd7ccbb45973cd9b02/tags/debugger/debugger.py#L7

core/tags: Remove debugger tag definition

---

core/keys/keys.py

Similar rationale to #944, but targets the more problematic command.

keys: Use real words for "dub quote"

---

apps/vscode/vscode.talon

This allows to run test in viscose by voice.
I tried to follow the contribution guidelines `[subject][verb]`
`jetbrains.tailon` defines `run test`
Let me know what you think.

vscode: Add commands to run tests

---

lang/javascript/javascript.py

There's currently no module implementation for this function, so this leads to a lot of log spam when editing any javascript or typescript file:
```
2022-11-11 12:48:05 WARNING actions: skipped because they have no matching declaration: (user.code_type_dictionary)
2022-11-11 12:48:05 WARNING actions: skipped because they have no matching declaration: (user.code_type_dictionary)
2022-11-11 12:48:05 WARNING actions: skipped because they have no matching declaration: (user.code_type_dictionary)
2022-11-11 12:48:05 WARNING actions: skipped because they have no matching declaration: (user.code_type_dictionary)
2022-11-11 12:48:05 WARNING actions: skipped because they have no matching declaration: (user.code_type_dictionary)
```
Unless we know where this module function should go, it seems like …

javascript: remove `code_type_dictionary()`

---

.gitignore

Macs litter local directories with .DS_Store. Git should ignore them.

git ignore .DS_Store as #1022 but without extra commits

---

apps/iterm/iterm.talon
core/tags.py
tags/terminal/readline.py

This PR implements `delete_line` for iterm. Although, I wonder if this should be in generic_terminal.py? I think most terminals have the same keybindings.

Implement delete line action for iterm

---

README.md
tags/terminal/unix_shell.py
tags/terminal/unix_utilities.py
tags/terminal/unix_utilities.talon

In my daily work, I use a lot of common utilities in my terminals. I extended the `generic_unix_terminal` tag in order to make it easy to run common commands and assemble pipes.
Some of the utilities are quite short and could be replaced by spelling their names out (e.g. `df`) or dictating the word (e.g. `touch`, `true`). I opted to include those cases since I found the flow to be better this way. I assume the accuracy also benefits for words with close pronounciation, like `false`/`falls`.
For several commands, I also added flags which I commonly use. It might be argued that adding those flags introduces unnecessary clutter. Including them was down to personal preference, again. It might make sense to remove them from the `default_unix_utilities.csv` file. The inclusion of flags in the …

Add common unix utilities to the generic unix terminal

---

apps/tmux/tmux.py
apps/tmux/tmux.talon

tmux panes and windows are pretty analogous to talon splits and tabs. this implements the appropriate actions to support split and tab commands for tmux. users can add the tmux tag to their terminal/whatever to enable.

implement splits and tabs for tmux

---

lang/python/python.talon

Currently we have `state raise` and `raise {user.python_exception}` commands. This annoyingly requires you to remember whether you are going to say an exception name in order to know whether to say `state` or not. Simpler to always allow it.

python.talon: allow optional "state" before "raise"/"except"

---

apps/git/git_arguments.csv

this is an argument to `git branch` which is confusingly similar to `--set-upstream` but apparently `git branch --set-upstream` is deprecated.

git_arguments.csv: add --set-upstream-to

---

plugin/desktops/desktops_mac.py

At least for me on a MacBook pro on ventura, the current implementations of `window_move_desktop_{left,right}` produce an error, and even if they didn't they would use keybindings that don't work by default. This fixes that error and uses the default keybindings of ctrl-left/right.

make window management on mac work a bit better

---

tags/terminal/terminal.talon

You can now do `katie root` to go to `/` and then `katie dir root` to go to `/root`.

Allow changing to directories with names conflicting with talon commands

---

core/app_switcher/app_name_overrides.linux.csv

I don't have the link (it's older than 90 days, no longer searchable) but at least one other person ran into this issue/confusion, I found this fix via the Talon Slack.

Add Gnome-terminal support to app_name_overrides.linux.csv

---

core/windows_and_tabs/windows_and_tabs_linux.py
core/windows_and_tabs/windows_and_tabs_mac.py
core/windows_and_tabs/windows_and_tabs_win.py

Removes some comments created by the action migration script. Perhaps we should have TODOs to implement `app.tab_detach` on various platforms instead? I'm not sure there _is_ a standard way to accomplish that action, though.

remove bogus comments created by migration script

---

BREAKING_CHANGES.txt
core/deprecations.py

Implementation of a variant of the action deprecation system from #940 that also covers captures and voice commands.
This system should let us take care of the breaking changes proposed in #928 and #939 smoothly for example.

feat(#940): Implement action/command/capture deprecation process

---

core/edit/standard.talon

The current pad command leaves the cursor in the middle of two spaces. I think it would be much more convenient if we could say something like "pad equals" and have " = " with the cursor already at the end of the inserted text, making it easier to continue typing.

Add command for adding padding around symbols

---

apps/git/git.talon

The `git diff` command ought to be end-anchored, otherwise you can't follow it by another command (eg. `git diff say test` to produce "git diff test") as you can with the other optimistically executed git commands. I think I just forgot the end-anchor in my git.talon rewrite.

end-anchor git diff command

---

apps/firefox/firefox_mac.py

When editing text `cmd-left` and `cmd-right` just move the cursor to the start or end of the line. `cmd-[` and `cmd-]` don't have that issue.

Change actions shortcuts in go_back and go_forward in Firefox mac

---

core/edit/edit_mac.py

The default bindings for `edit.file_start` on mac presses `cmd-up cmd-left` (and `edit.file_end` is `cmd-down cmd-left`). I find this `cmd-left` to be redundant (at least in TextEdit and in Emacs, `cmd-up` goes to the start of the document, including the beginning of the line) and to produce bad behavior in, eg, web browsers, where `cmd-up` successfully scrolls to the top but then `cmd-left` goes back in history.
Are there some applications where this `cmd-left` is necessary?

edit_mac.py: omit cmd-left for file_start/file_end

---

apps/chrome/chrome.py

Add esc press to reset address bar if it has been edited before duplicating

Update chrome tab duplicate to include esc press

---

apps/windows_explorer/windows_explorer.py

Issue [called out in slack](https://talonvoice.slack.com/archives/CJ2EE3LEB/p1673705822738799) by user Gabriele. 
On their Windows 10 machine and my Windows 11 machine, app.exe for windows explorer is cased as "Explorer.EXE".
On non english machines, the title may not match the English "Windows Explorer", and so having an accurate exe matcher is essential.
Testing: I confirmed on my Windows 11 machine that (if I remove the app.name matchers), the context matches with the new capitalization, but not with the old capitalization.

alternate capitalization for windows_explorer app.exe

---

core/text/formatters.py

Non-formatter dictation (say/sentence commands, dictation mode) [uses "numeral"](https://github.com/knausj85/knausj_talon/blob/c830318a4aa96d3855e537c576fc79a5641aa98c/core/text/text_and_dictation.py#L44-L56) to trigger use of numerals, so I thought it would be nice for formatters to support "numeral" as well.
I'm not sure what you want to do about formatters also supporting the word numb.  Maybe 'say' and formatters should only use 'num' but I went with a minimally disruptive change until I get feedback.

formatters use 'numb' AND now 'numeral' to trigger numerals

---

BREAKING_CHANGES.txt
apps/i3wm/i3wm.talon

Also remove redundant 'port ten' command.
Replaces #928

Deprecate `murder`, add `shuffle flipper` to i3wm

---

core/create_spoken_forms.py
test/stubs/talon/__init__.py
test/test_create_spoken_forms.py

Currently `create_spoken_forms` can generate empty spoken forms if passed certain inputs (eg. the empty input). This prevents that, and also cleans up some code along the way.

simplify create_spoken_forms and avoid empty spoken forms

---

core/edit/edit.py
core/edit/edit_linux.py
core/edit/edit_mac.py
core/edit/edit_win.py

`select_word()` has several issues as per https://github.com/knausj85/knausj_talon/issues/1084.
Notably accidental selection of symbols and word selection breaking if the caret is before a new line.
This pull request aims to resolve these.
Note: This is only tested on MacOS, though it uses higher level functions for all operations, so I don't foresee any major issues on other operating systems.

Improve `edit.select_word()`

---

plugin/mouse/mouse.py

Fixes regression from this PR:
https://github.com/knausj85/knausj_talon/pull/1095/files#diff-bcc9a76bafcd0560a68b01c7c397581731a565bba524207313dbe16c972a80eeL254
Note that I don't have an eye tracker. So we need somebody with one to test pop to click still works when using control mouse and the legacy control mouse.

fix: Only pop to click when you have an eye tracker

---

apps/chrome/chrome.talon

Tab search command via ctrl/cmd + shift + A
There's already an implementation for firefox that uses the address bar, this pull request mimics that for Chrome

Add tab search command similar to firefox.talon

---

apps/chrome/chrome.py

On my Manjaro Linux machine, the browser Chromium appears with a executable name which is not yet recognized by `chrome.py`. This pull request makes chromium detect correctly for me.
As a side note: since multiple tags are connected by `or`, shouldn't the entire context match block for Linux be something like
```
os: linux
and app.exe: chrome
os: linux
and app.exe: chromium-browser
os: linux
and app.exe: chromium
```
Also, IMO the subsequent block could also be included (lines 25-28) in this, thus joining all `os: linux` matchers. 
If you agree, I'll gladly amend this in this PR.

Detect Chromium as a browser under Manjaro Linux

---

core/modes/dictation_mode.talon

Making it consistent with text.talon, where "nope that" is an alternative for "scratch that".

added "nope that" etc. to dictation mode

---

plugin/dropdown/dropdown.talon

rename `dropdown` command to `drop down` to fix #1087.

fix #1087 by renaming `dropdown` to `drop down`

---

apps/git/git_arguments.csv

Allows users to say eg. `git reset origin main` to produce `git reset origin/main`.

git_arguments.csv: add origin/main, origin/master

---

plugin/paste_to_insert.py
settings.talon

Adds a plugin that lets users use `user.paste` to insert text longer than certain # of characters. Disabled by default, with a commented-out setting in `settings.talon`.

add paste-to-insert plugin & setting

---

core/noise.py
plugin/mouse/mouse.py
settings.talon

This PR addresses #755 and replaces #858 . It does two things:
1. The pop noise triggers an action `user.noise_trigger_pop`.
2. The existing setting `user.mouse_enable_pop_click` gets a third value '2' which says always pop to click.
The first point lets people 'take over' the pop noise so they don't have to worry about whatever knausj talon is doing with it. It also provides a nice scaffold in case you want it to do different things in different contexts.
The second point differs a bit from the pop_click = yes/no boolean discussed in #755 . This is for backwards compatibility. With a yes/no setting I'd either have to turn it on by default for people without eye trackers (i.e. undo https://github.com/knausj85/knausj_talon/pull/1119) or turn it off and break the expected behaviour for most …

feat(#755) Pop to click setting for all users

---

apps/firefox/firefox.py
apps/firefox/firefox_mac.py
apps/firefox/firefox_win_linux.py

If the user uses German menus that shortcut doesn't work and opens the file "Datei" menu instead.
Pressing F6 before pressing ctrl-l also ensures that the command will work if the user is focused in the devtools (instead of clearing the console).

Fix issue with alt-d not always focusing address bar in Firefox Windows

---

core/abbreviate/abbreviate.py
core/create_spoken_forms.py

This PR implements the results of the discussion in #1048 (and replaces that PR); it seems worthwhile to have abbreviations in the settings/*.csv system.

feat: Allow abbreviation customisation via settings/abbreviations.csv

---

core/homophones/homophones.py
core/homophones/homophones_open.talon

- Switch to using a tag instead of a mode 
- Call raise_homophones to ensure the quick replace functionality is used for selected words with only two homophones (addresses #1098)

Minor homophone fixes

---

lang/markdown/markdown.py
lang/markdown/markdown.talon

Markdown
* add `heading` or `header` alternatives for `level`
* fix `level` to edit at line start
* add `list` commands
* add `link` command
* add more code block languages: `ruby`, `shell`, `bash`, `json`

add lists, link, more code block options; improve level

---

core/keys/keys.py

small cleanup. drop the `default` prefix, it means nothing; use `str.split()` instead of `str.split(" ")`; use `enumerate` instead of a `numbers` array; add a comment explaining what the lists are for.

keys.py: simplify number key & function key handling a bit

---

apps/emacs/emacs_commands.csv

I think these are supposed to match `emacs.talon`?
```
buffer next: user.emacs("next-buffer")
buffer last: user.emacs("previous-buffer")
```

fix buffer next/buffer last

---

core/text/text_and_dictation.py

make it consistent with the formatter_immune capture in formatters.py, which has both numb and numeral

add numb as number prefix for prose formatting

---

apps/emacs/emacs.py

without this the new code doesn't activate on Windows. tested on Mac to make sure the matchers are not not conflicting

match emacs on windows

---

core/windows_and_tabs/window_management.talon

Action is implemented on all platforms, but for some reason no spoken form 🤷‍♂️

Add "window hide"

---

plugin/screenshot/screenshot.py

As part of writing a screenshot tool a long time ago, I changed `screenshot_rect` to a user action. As I'm hoping to eventually push or share the other tool for others to use, I figured I'd push this change.
For reference the other tool is called shotbox https://github.com/fidgetingbits/knausj_talon/tree/master/plugin/shotbox, and the usage of this action is specifically https://github.com/fidgetingbits/knausj_talon/blob/master/plugin/shotbox/shotbox.py#L659
I vaguely recall when I wrote this the general consensus was that we shouldn't be importing other local python files (I think because of potential negative affects on talon dynamic module reloading), which is why I did this as a user action instead of just `from .. import screenshot_rect`. If this is no longer the case than it may be …

Switch screenshot_rect to become a user action

---

apps/emacs/emacs.py
apps/emacs/emacs.talon
apps/emacs/emacs_commands.csv

pop-mark isn't an emacs command (only a function) and doesn't do what we want anyway. The keybinding it was listed with (ctrl-u ctrl-@) has the intended behavior, which is to invoke pop-to-mark-command. This PR means that we'll now do the right thing if `user.emacs` has to fall back to `M-x` or if it gets overridden to use RPC instead of keybindings.

use pop-to-mark-command not pop-mark

---

core/edit_text_file.py

We have more setting CSVs now. I've added them and also alphabetized the list.
It would be nice if we didn't have to do this manually but somehow derived it from calls to the settings-reading machinery. Not sure how to do that.

update talon_settings_csv list

---

core/keys/keys.py

Even though most keyboards do not have F13-F20, they are valid keys and some people use them, especially people with disabilities that they use alternate input devices like foot pedals.
My foot pedals are mapped to keys {F13, F14, F15} and that really simplifies creating "listeners" for the pedals.  It is also good that I can simply say F13 to get Talon to trigger those same listeners.

add F keys 13-20

---

tags/line_commands/line_commands.talon

`select_range` already includes the `jump_line` action.

Remove unneeded jump in clear line command

---

apps/tmux/tmux.py

Make it possible to configure the modifier key for the people that use alternative keybindings (like I do with `alt-a` :smile:).
This pull request also updates how windows are switched to use the keybind and numbers from 0 to 9 if possible, for a slightly faster user experience.

Make the tmux modifier key configurable

---

core/edit/edit_mac.py

The `edit.find(text)` implementation for Linux and Windows insert the text:
https://github.com/knausj85/knausj_talon/blob/38cb583db62593165c9938dd481b5f2b159e4d53/core/edit/edit_linux.py#L94-L96
https://github.com/knausj85/knausj_talon/blob/38cb583db62593165c9938dd481b5f2b159e4d53/core/edit/edit_win.py#L94-L96
The Mac implementation ignored the text parameter however.
This sets the [find pasteboard](https://blog.robenkleene.com/2019/08/26/the-move-find-replace-using-the-find-pasteboard-in-macos/) if `text` is passed.

edit_mac: Set the find pasteboard

---

core/app_switcher/app_switcher.py

I have experienced this with a desktop file that contains `Terminal=false` twice for some reason

don't bail out of get_linux_apps if one desktop file fails

---

BREAKING_CHANGES.txt
CONTRIBUTING.md
README.md
apps/README.md
apps/talon_repl/talon_repl.talon
apps/vscode/command_client/README.md
core/app_switcher/app_switcher.py
core/deprecations.py
core/edit/edit.py
core/edit_text_file.py
core/user_settings.py
lang/talon/talon.py
lang/talon/talon.talon
plugin/talon_draft_window/README.md
plugin/talon_draft_window/draft_talon_helpers.py
plugin/talon_draft_window/draft_window.talon
plugin/talon_helpers/talon_helpers.talon
test/stubs/talon/grammar.py

https://github.com/talonhub/community/issues/935. We're not in ~Kansas~ knausj anymore...
This updates:
- The main title of the README (as well as most references therein) and adds a note about our origins. [View here]( https://github.com/talonhub/community/tree/rebrand)
- The cloning instructions in the README.
- (This might be up for debate; do we want people to `git clone https://github.com/talonhub/community community`? Some users might end up with two copies. I think @lunixbochs had a plan to check for if people have both knausj and community cloned duplicative side by side by mistake.)
- GitHub's web UI recommends `https://github.com/talonhub/community.git` as the HTTPS URL, but our old instructions did not include the `.git` suffix. What do we want to do?
- All GitHub links in the …

`knausj`: rebrand, honor original creator

---

core/app_switcher/app_switcher.py

Regression from https://github.com/talonhub/community/pull/1197 . Issue is the code will populate the self.launch list with something like:
```
{
'my app': '/Applications/My App.app'
}
```
Then later in `actions.user.switcher_launch` `shlex.split` would turn that into `cmd = '/Applications/My', args='App.app'`. Quoting the path makes it treat the whole path as one unit.

fix: Handle spaces for 'launch <appname>' in OSX

---

lang/typescript/typescript.talon

This adds a few commands for some TypeScript type operations:
- `type union/intersect` after a type to union or intersect it with another type
- example: `type union undefined` will make a type possibly undefined ` | undefined`
- `state type` to start a `type` statement
- `as const` to insert `as const` at the end of an expression

typescript: Add type operation commands

---

core/modes/sleep_mode.talon

`mouse_enable_hiss_scroll` currently remains on in sleep mode when enabled. This fixes that, replicating the behavior of other noise/mouse settings.

Always stop mouse scroll down using hiss noise in sleep mode

---

core/app_switcher/app_switcher.py
plugin/talon_helpers/create_app_context.py
plugin/talon_helpers/talon_helpers.talon

`"talon create app context"` will generate a new folder in `apps` with a Talon and a python file. 
Example from visual studio code: 
`apps/visual_studio_code/visual_studio_code.talon`
```talon
app: visual_studio_code
-
```
`apps/visual_studio_code/visual_studio_code.py`
```py
from talon import Module, Context, actions
mod = Module()
ctx = Context()
mod.apps.visual_studio_code = r"""
os: windows
and app.exe: Code.exe
"""
ctx.matches = r"""
os: windows
app: visual_studio_code
"""
```

Added voice command to create Talon application context

---

apps/tmux/tmux.py
apps/tmux/tmux.talon

Done by having the context for matching tmux be a more restrictive match than that of the terminals.
This was modeled after the matches for the in-browser Slack and Teams apps.

Prefer tmux splits and tabs over containing terminal

---

core/windows_and_tabs/window_snap.py

The existing snap spoken forms are rather verbose, requiring the user to think in terms of fractions.
In day-to-day use, I find it helpful to have "small" and "large" as shorter/simpler aliases. Let's add these as alternates; people can continue to use the old forms if they prefer them.
`"left third"` => `"left small"`
`"bottom right two thirds"` => `"bottom right large"`
I also added an action that takes the position name as a string, instead of the dataclass. This allows users to snap to a specific window position from a Talon file, which wasn't previously possible since you couldn't pass the `RelativeScreenPos` object from Talonscript (this was requested from a few users before).
`user.snap_window_to_position(position_name: str)`

Added simplified spoken forms for window snap

---

apps/jetbrains/jetbrains.py

I noticed PhpStorm isn't recognized as a JetBrains editor on my Mac, so I added it.

Add PhpStorm to Jetbrains App List

---

pyproject.toml

Suppresses `Instance methods should take a "self" parameter` warnings in editors that use pyright (eg VSCode). Due to the way Talon defines action classes, these warnings are almost always noise in any Talon user file set

Don't report error for self parameter name

---

apps/mintty/mintty_win.py

The cmd.exe window that the subprocess module uses does not start hidden, and so steals focus from the mintty window.  This focus stealing may happen several times.
The stolen focus is not restored unless Talon sets the focus via the focus command, and inhibits usage of physical input devices until that focus is restored.

Hide cmd window for mintty when setting cyg_path.

---

apps/firefox/firefox.py

Pretty self-explanatory. This was needed for Talon to recognize the Firefox binary from the stable Debian repository, which is an extended support release version.

Add recognition for ESR versions of Firefox

---

core/windows_and_tabs/windows_and_tabs.py
core/windows_and_tabs/windows_and_tabs_linux.py
core/windows_and_tabs/windows_and_tabs_mac.py
core/windows_and_tabs/windows_and_tabs_win.py

The current implementation of "window next/last" doesn't really work. This is an implementation using the Talon ui/window api similar to how focusing applications works.

Added Talon based implementation for `app.window_previous/next`

---

core/edit/edit_mac.py

`cmd-shift-s` is typically reserved for `Duplicate` or `Save As…` on the Mac. Save all, where it exists, is typically `cmd-alt-s`.

Fix save all keyboard shortcut on the Mac

---

apps/vscode/vscode.talon

- These shortcuts are unambiguous for navigating snippets in VSCode
Thanks to @AndreasArvidsson for [the example](https://github.com/AndreasArvidsson/andreas-talon/blob/59cfecd26c3a01e72847364f6cafb5cdb8202b1b/apps/vscode/vscode.talon#L239)

Add recommended snip shortcuts

---

lang/rust/rust.py
lang/rust/rust.talon

These realistically have no business being actions:
- They're only used in one place.
- They're extremely simple, as they're only one line.
- There is no use-case for overriding them.
This inlines the actions into the Talonscript.
Closes: #1323

rust: Inline Rust-specific one-line actions

---

lang/tags/imperative.py

No language implements this, and there's no voice command for this action either.

lang: imperative: Remove unused code_state_continue action

---

apps/jetbrains/jetbrains.py

Now jetbrains rider works correctly like the other jetbrains products

Update jetbrains.py to include rider for mac

---

lang/c/c.talon
lang/csharp/csharp.py
lang/csharp/csharp.talon
lang/css/css.py
lang/css/css.talon
lang/java/java.talon
lang/javascript/javascript.py
lang/javascript/javascript.talon
lang/php/php.py
lang/php/php.talon
lang/proto/proto.talon
lang/r/r.talon
lang/rust/rust.py
lang/rust/rust.talon
lang/scala/scala.py
lang/scala/scala.talon
lang/tags/imperative.py
lang/terraform/terraform.talon

Several languages had the same, or similar, copy-pasted implementations of `code_block` to insert braces and leave the cursor on a blank line between them. These all assume the editor will appropriately expand <kbd>enter</kbd> between brackets, which isn't true for all editors.
The C# implementation implemented the same idea, but appears to assume <kbd>enter</kbd> _isn't_ expanded.
Furthermore, some C-like languages were missing a `code_block` impl entirely.
Similar to #720, this adds a common implementation for braced code blocks, which can be overridden on a per-editor basis, and adds the tag to the appropriate languages.

lang: Add tag for brace-delimited code blocks

---

plugin/command_history/command_history.py
plugin/paste_to_insert.py
tags/file_manager/file_manager.py

```
2024-01-03 09:31:45.551 WARNING C:\knausj_talon\tags\file_manager\file_manager.py:317: DeprecationWarning: SettingsDecl: setting.get() is deprecated. Use settings.get('user.file_manager_auto_show_pickers')
if gui_folders.showing or setting_auto_show_pickers.get() >= 1:
```

avoid warnings due to change of apis in talon

---

lang/markdown/markdown.talon

This avoids issues with extra closing backticks in VSCode due to automatic delimiter closing

Switch markdown code blocks to use snippets

---

plugin/mouse/mouse.py
plugin/mouse/mouse.talon

previously they would sporatically work but the zoom overlay window would stay open

allow mouse commands to work in zoom mode

---

.pre-commit-config.yaml

There should be a single source of truth for Black's config. This makes `pyproject.toml` that source of truth.

pre-commit: Remove black args

---

apps/git/git.talon

Double quotes allow you to use contractions (don't, isn't, etc) in the commit message without having to escape them. On the other hand they mean that some special characters need escaping. I find that double quotes are a better default for me. If other folks disagree, feel free to nix this PR.

use double quotes for git commit message

---

core/mouse_grid/mouse_grid.py

I use this as I have commands which want to ensure a consistent moue grid state before and after they have run.
e.g. If the mouse grid was active before the command runs, they leave it active afterwards, if the mouse grid was closed then it is left closed.

mouse grid: add method to test if mouse grid is active.

---

apps/nautilus/nautilus.py

on Linux Mint MATE the default file explorer is a fork of Nautilus and is called Caja

added app name Caja (fork of Nautilus)

---

apps/gnome_terminal/gnome_terminal.py

on Linux Mint MATE the default terminal app is a fork of Gnome-terminal and is called Mate-terminal

added app name Mate-terminal (fork of Gnome-terminal)

---

lang/javascript/javascript.py
lang/ruby/ruby.py
lang/ruby/ruby.talon
lang/tags/operators_assignment.py
lang/tags/operators_assignment.talon

- without this, saying `op or equals` would be interpreted as `op or`
followed by `equals`, which results in a syntax error `|| =`

Add ruby op-or-equals command

---

README.md
core/modes/sleep_mode.talon
plugin/mode_indicator/README.md
plugin/mode_indicator/mode_indicator.talon
plugin/mouse/mouse.py
plugin/talon_draft_window/draft_window.talon
settings.talon
tags/file_manager/file_manager.py

Turn boolean settings in `mouse.py` and `file_manager.py` into proper booleans. For now, I've held off on converting the corresponding  `.talon` settings to boolean literals per #1296, but happy to do that too if there are no concerns.

Convert boolean settings to boolean

---

plugin/mouse/mouse.py

Changes `continuous_scoll_mode` with a missing `r` to `continuous_scroll_mode`.

Fix typo in `mouse.py` variable name

---

README.md
settings.talon

Suggested update to make settings descriptions clearer and more consistent.

Update settings descriptions

---

plugin/mouse/mouse.talon

I would regularly say `drag start` which would cause an asterisk to be inserted.

mouse: adding synonyms for starting left drag.

---

lang/c/c.py
lang/c/c.talon

Removes a [dead setting](https://github.com/talonhub/community/pull/1360#issuecomment-1902757989) from the c code language.

Remove unused setting from c code language

---

core/app_switcher/app_name_overrides.windows.csv

It doesn't appear iTerm is available on Windows, so this should be safe to change.

Update app_name_overrides.windows.csv to use Windows Terminal instead of iTerm2

---

apps/adobe/adobe_acrobat_reader_dc.py
apps/conemu/conemu.talon
apps/jetbrains/jetbrains.py
apps/kindle/kindle.py
apps/nitro_reader/nitro_reader_5.py
apps/sumatrapdf/sumatrapdf.py
apps/vscode/vscode.py
core/app_switcher/app_name_overrides.linux.csv
core/app_switcher/app_name_overrides.mac.csv
core/app_switcher/app_name_overrides.windows.csv
core/app_switcher/app_switcher.py
plugin/talon_helpers/create_app_context.py
plugin/talon_helpers/talon_helpers.py

- Update mixed-case app.exe: matchers to work with public and beta Talon.
- Update app switcher to work with public and beta Talon.

Update app.exe matching to work with both public and beta Talon

---

BREAKING_CHANGES.txt
core/mouse_grid/mouse_grid_open.talon
core/numbers/numbers.py
core/numbers/numbers.talon
core/numbers/numbers_unprefixed.talon
core/numbers/numbers_with_prefix.talon
settings.talon

- Attempt to implement optional numb prefix
- The tags need to be logically combined
- Respond to suggestion that the mouse grid should not be considered

configurable number prefix without mouse grid

---

apps/vscode/vscode.py

The default value for "zoom reset"  defined in edit_win.py is "ctrl-0".  This does not work in VS Code. The PR  attempts to fix this.

define "zoom reset" for VSCode

---

core/text/text_and_dictation.py

We avoid needing to peek left if both:
1. The string being inserted never needs space before it (eg: it is a period).
2. The string being inserted does not change under auto-capitalization.
This PR extends condition (2) to include the case where `auto_cap = False` has been passed, so we are not doing auto-capitalization at all.

micro-optimization for dictation_insert

---

core/help/help_open.talon

We use "next/last" in various commands, but help uses "next/previous". This matches the button labels (which are "previous" because it's more self-explanatory than "last"), which is good, but is inconsistent with other commands, which is bad. I suggest we support both.

allow "help last" as synonym for "help previous"

---

apps/emacs/emacs.talon
apps/emacs/emacs_commands.csv

Adds more emacs commands, mostly `xref` commands but also `other-frame` and `visit-tags-table`. Also sorts `emacs_commands.csv`.

More emacs commands, including xref commands (go-to-definition)

---

core/help/help.py

Currently if the user uses  `user.help_list()` and passes in a list with multiple implementations, the first list will always be chosen by virtue of the code using index `[0]`. However, it should show the currently active implementation by using `[-1]`. This is probably unintended behavior. 
Without this change, it is impossible to use `user.help_list` with the `user.snippet` list that is contextually overridden based on programming language type. I would like to add a `help snip` command and that would depend on this.

Use active list with help_list

---

plugin/talon_draft_window/draft_talon_helpers.py

Fixed warning about using `setting.get()`
Changed to use `settings.get(setting_name)`
Closes #1473 
See also https://github.com/talonhub/community/pull/1351, https://github.com/talonhub/community/pull/1349

draft_talon_helpers: migrate away from deprecated settings usage

---

lang/tags/functions.py

A tiny cleanup in line with the recommendation I pushed to @CodesAway's  https://github.com/talonhub/community/pull/1474.
With the move to `settings.get()`, we should no longer assign settings to module-level variables, since it's no longer needed, and we don't want anyone to use them by mistake. These aren't being used, so let's just remove them.
This means you can now grep for `= mod.setting(` to search for old usages, and it comes up clean on main.
(To my surprise, this code was using `settings.get()` from the beginning when @wenkokke wrote it)

functions: remove unused `setting_` module variables

---

core/help/help.py

This broke in a recent update.

Fix bug where you couldn't select help context by index

---

core/modes/modes_not_dragon.talon

Ideally I would remove `engine.py` but I don't really understand how this file interacts with dragon. I do know that using mimic is not needed for conformer. 
Related to #1503

Don't use mimic when not using dragon

---

core/noise.py

Right now noises in the core directory is dependent on the implementation in of mouse that is in plugin. 
Fixes #1400

Made default noise implementations noop

---

core/screens/screens.py

Stop using `get_sorted_screens` an use Talon screen ordering instead.
Fixes #841

Use Talon screen ordering

---

core/mouse_grid/mouse_grid_open.talon

Currently you can only close the mouse grid with `grid off`, however this never felt very intuitive to me when learning to use the repository. I would often struggle to remember how to close it and this was annoying as it can be quite obstructive
Elsewhere in the repository to close something it is often either `<object> hide` such as `manager hide` or `<object> close` such as `help close`
As such this pull request adds the option to close the mouse grid with close and hide. 
But I'm not sure if this is just a personal opinion, happy to discuss in this pull request

Add more options for closing the mouse grid

---

core/edit/edit.talon
core/edit/edit_navigation_steps.py
core/keys/keys.py
core/keys/keys.talon

Implemented new more powerful navigation grammar
* go left
* go left left down
* go 5 left 2 down
*  go word left
* go 2 words right
* go 5 left down down 4 words left
This is fully backwards compatible with the existing `go left`, `go word right` and `go left left down down` grammars. Only here combining them in a single (more powerful) command

Added navigation steps command

---

core/edit/edit_command.py

Update use the correct action identifier
Should match this file
https://github.com/talonhub/community/blob/bc88b144e69cf4afedb0e080bab3085e20365d69/core/edit/edit_command_actions.talon-list#L9
Without the correct identifier whenever someone says `"cut line"` they won't actually get the implementation of `user.cut_line()`

Update edit identifier `cutToClipboard`

---

core/edit/edit.py
settings.talon

The default time out for `clip.capture()` is 0.5s. You run into this every time you call `selected_text()` on an empty selection. I've been running with 0.1 for over a year with no problems. That might be a bit to aggressive for community, but 0.25 shouldn't be any problems. Just in case I added a setting so people with slower (or faster) machines can change this.
Fixes #1210

Added setting for selected text timeout

---

plugin/draft_editor/draft_editor.py

Sometimes submitting drafts can fail as it cannot find the window to focus on to submit the draft. As it is currently that draft can then be lost.
These changes catches any errors when trying to focus on the previous window, and informs the user how to fix this.

Catch and handle errors when closing draft editor

---

core/homophones/homophones.py

added a line to function update_homophones in homophones.py to remove words that are empty strings from the list of homophones created from each line of the CSV file. The issue is that CSV file format is not standard, and programs like MS Excel try to force each line to have the same number of "cells" (i.e. commas). This results in almost every line having on extra comma which is read as a "word" that is an empty string, and then these empty string "homophones" are matched with other words' empty string homophones resulting in every word being a homophone of every other word in the file.

Handle blank entries in homophones.csv

---

core/text/phrase_ender.talon-list
core/text/text.talon
core/text/text_and_dictation.py

Instead of just `"over"`, adds a list of symbols that can be used to end/terminate a phrase. Also supports values for these phrases so you can end your phrase with a symbol that will be inserted. eg `"say hello there slap"` => `hello there\n`
This implementation is quite simple with the drawback that there is no synchronization between the spoken forms in this list and existing voice commands for adding these symbols. 
Slack reference
https://talonvoice.slack.com/archives/C9MHQ4AGP/p1723643676364569

Added phrase enders list

---

core/abbreviate/abbreviate.py

Today a user gets warnings in the Talon log if the abbreviation value is not speakable

Skip non speakable abbreviation values

---

apps/talon/talon_repl/talon_repl.py
apps/talon/talon_repl/talon_repl.talon

Similar to #1451 this uses a context using not forced language to override `code.language` and enable python lang features inside the talon repl. It also makes the title matching more restricting, as this currently matches on anything with repl in the name, and there are many repls that aren't talon or python...
I also enable readline so that common navigation commands work inside.

Enable readline and python tags in talon repl

---

BREAKING_CHANGES.txt
core/system_paths.py
migration_helpers/migration_helpers.py

Use `hostname:` rather than `host:` to (correctly) match a hostname.
Generate a default `system_paths-<hostname>.talon-list` akin to the
prior CSV.
Also makes some minor tweaks to the generated spoken forms:
- only use "profile" for Windows; "home" for other platforms
- add "talon recordings" (because I want to use it in the wiki)

Fix regressions in system path support from #1268.

---

core/keys/arrow_key.talon-list
core/keys/function_key.talon-list
core/keys/keypad_key.talon-list
core/keys/keys.py
core/keys/letter.talon-list
core/keys/mac/modifier_key.talon-list
core/keys/mac/special_key.talon-list
core/keys/number_key.talon-list
core/keys/win/modifier_key.talon-list
core/keys/win/special_key.talon-list

- does not port punctuation_words or symbol_keys, as these are used by create spoken forms
- adds support for keypad keys

Convert keys to .talon-list where possible

---

core/file_extension/file_extension.py
core/modes/language_modes.py
lang/elixir/elixir.py
lang/elixir/elixir.talon

I am not an elixir expert but I think this covers the basics. I wasn't able to find an elixir example in community forks so I put this together on my own. 
When this gets merged I will be on the lookout for feedback to improve it incrementally in subsequent changes.

First pass at adding a language mode for elixir

---

core/keys/keypad_key.talon-list
core/keys/keys.talon
core/keys/mac/modifier_key.talon-list
core/keys/mac/special_key.talon-list
core/keys/win/special_key.talon-list

All platforms:
- keypad_enter
- insert (inadvertently removed in #1554)
- Allow dictating keypad keys directly without "press"
Mac:
- "function"/"globe" for globe/fn modifier (increasingly used by the OS)
- "return" for return (as printed on Apple keyboards)
- "enter" for [keypad] enter
The only one I'm a bit worried about is the last one. It is correct per Apple's definitions but it's possible some users are used to saying "enter" (though it's not the correct name for the key) and will get unexpected behavior; in most Mac apps I've tried, Return and Enter behave identically.

Add more per-platform keys in talon-lists.

---

apps/vscode/vscode.py

Implements the tab clone command in vscode. As you can't have two tabs of the same file open in the same tab group it splits the window vertically which clones the tab left and right.
Also cleans up the functions, grouping all of the splits,py, and tabs.py functions together

Add tab clone command and improve file organization

---

core/mouse_grid/mouse_grid_open.talon
core/numbers/numbers.py
core/numbers/numbers_unprefixed.talon
settings.talon

This is a source of misrecognitions for new users. We have now had the deprecation message for nine months so I think it's fine to remove this.

Remove unprefixed numbers command

---

apps/vscode/vscode.py

It looks like the vscode command has changed.

Fix maximize split VSCode action

---

tags/browser/browser_mac.py

On mac os, I was having an issue with `browser.host` which can be reproduced with the following steps.
1. put the following in a talon file:
```
browser.host: www.google.com
-
testing: app.notify("testing")
```
2. in firefox, open google.com
3. say "testing", verify you get the notification
4. open dev tools, focus another app, and then focused firefox again
5. say "testing", you will NOT get the notification 
It seems that in this scenario browser.host context matcher is no longer respected. I hunted down the issue to this line.
My change is probably pretty brittle, but at least works on mac (the only operating system where this code applies) chrome and firefox.
Some slack discussion took place here: https://talonvoice.slack.com/archives/C9MHQ4AGP/p1724030602939929

Select final web area to avoid devtools

---

core/navigation/navigation.py

Swap go back and go forward commands on Mac.

---

core/help/help.py

Per aegis, it is extra bad to be calling methods on the registry and upcoming Talon versions will break this usage.
Could likely remove our own cache now, but wanted to get this potential break-fix in first.

Use registry.last_active_contexts instead of registry.active_contexts() in help system.

---

apps/obsidian/obsidian.py
apps/obsidian/obsidian.talon
core/modes/language_modes.py
core/modes/language_modes.talon

This makes some tweaks to language modes:
1. It adds a list of special-cased files that are mixed into the determination of the language, so you can return a language for things even if the file extension itself doesn't imply the language. The languages included aren't actually implemented in community, so I can keep the list empty if preferred, but I figured I'd keep it populated at first to give an example of why it's useful.
2. Adds a command to show the currently forced language
3. #1256 semi-recently went the route of removing language-specific tags. This has the side effect (afaict) that an app that doesn't expose the file extension in its title can no longer force a language (previously it would just `tag: user.<lang>`). Given we removed the tags I assume we don't want them back, …

Allow apps to force lang via code.language and add special cased files

---

core/text/formatters.py

Remove all the symbols from the code formatter capture.
Before: `"hammer one plus"` -> `One+`
Now: `"hammer one plus"` -> `OnePlus`
Fixes #1575

Remove symbols from code formatters

---

plugin/mouse/mouse.py
plugin/mouse/mouse_scroll.py

mouse.py is to large so I have extracted all the code related to mouse growling into a separate file. I also took the liberty to clean up the code an simplify as much as I could.

Refactor mouse scrolling code

---

core/modes/modes.py

None of these modes are used in community and even if they were they should have been tags instead.
Fixes #603

Remove unused modes

---

core/text/text.talon

remove `proud <user.word>` command due to redundancy from `{user.word…_formatter} <user.word>` command

remove redundant `proud <user.word>` command 

---

apps/powershell/README.md
apps/powershell/powershell_win.py
apps/powershell/powershell_win.talon

Currently when using powershell the title is forced to be updated after every directory change automatically
This is updated by inserting a command into powershell which updates the title, which clutters your terminal quite quickly.
The better solution is that the user updates their powershell prompt function so that this is done automatically, and then turn off the forced title refresh.
This pull request adds the talon setting to turn off the automatic forced title refresh, and adds a readme on how to do this.
Additionally I've changed open file to actually automatically open the file. If the user just wants to insert the string of the file they can already use select file command. 
I'm not sure if it's best to add the powershell specific readme file or add the documentation in the …

Update powershell to add option not to update the title

---

apps/dock/dock.py
apps/dock/dock.talon

Implement app Exposé with accessibility since the CoreDock notification broke

---

core/edit/edit_command_modifiers.py

Currently edit modifier "way left" and "way right" uses actions.user.select_line_start/end
This action based upon it's comment description should be the same as actions.edit.extend_line_start/end but they have different behaviour.
Behaviour when using the current user action: before doing an extend line action it does a edit.left action, leading to a different selection than intended.
Prior to the move to the compound edit command `select way left` was using the actions.edit.extend_line_ action
I'm also not sure if the older action is actually necessary when we have the edit versions?

Fix select/copy/cut way left/right

---

apps/jetbrains/jetbrains.py

The other ce mappings don't work on windows.

Add missing jetbrains port mapping

---

BREAKING_CHANGES.txt
core/deprecations.py
plugin/mouse/mouse.py
plugin/mouse/mouse.talon
plugin/mouse/mouse_scroll.py

`talon_plugins` has been removed in the latest beta. As far as I know there is no replacement to check if we are zoomed in or not.
Fixes https://github.com/talonhub/community/issues/1637

Remove dependency on `talon_plugins`

---

apps/jetbrains/jetbrains.py

Fixes this:
```
2025-01-06 13:35:35.631 ERROR     9:            talon\scripting\talon_script.py:721| 
8:            talon\scripting\talon_script.py:314| 
7:                 talon\scripting\actions.py:88 | 
6: user\community\apps\jetbrains\jetbrains.py:171| actions.user.idea("action NextTab")
5:                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
4:                 talon\scripting\actions.py:88 | 
3: user\community\apps\jetbrains\jetbrains.py:146| app.notify(e)
2:                                                 ^^^^^^^^^^^^^
1:                               talon\app.py:69 | 
TypeError: argument 'title': 'FileNotFoundError' object cannot be converted to 'PyString'
[The below error was raised while handling the above exception(s)]
```

Fix exception type error

---

apps/vscode/command_client/README.md

We moved the deployed repo for people not on community into the `cursorless-dev` organization; updating deploy instructions. We also renamed `master` to `main` to be consistent with our other repos

Move command_client repo

---

plugin/draft_editor/draft_editor.py

Current Talon beta raises an exception rather than returning `None` if you try to read a setting that isn't declared yet. This is intentional behavior — it exposes bugs like this one.
Also fixes `user.draft_editor*` tags not being set at startup.

Avoid race reading user.draft_editor setting at startup.

---

core/windows_and_tabs/window_snap.py

The snap command is not respecting the new talon list. It was skipping the actual snapping of the windows. This restores that behavior.
fixes #1684

Bugfix for snap window

---

apps/jetbrains/jetbrains.py

add matchers for goland, intellij CE and local plugin development

add macos matchers for more jetbrains products.

---

apps/vscode/vscode.py

Reverts #1677
These actions doesn't work in all scenarios. eg a save dialog.

Revert vscode clipboard actions from #1677

---

core/snippets/snippets_parser.py

The trailing new line after the `---` separator was incorrectly counted resulting in an incorrect line number for error messages.
Also remove unnecessary logic preventing error message about duplicate keys if those keys are invalid. Complicating the code just so we don't show a duplicate key and invalid key error isn't necessary.

Fix bug in snippet parser line calculation

---

lang/tags/imperative.py

`self` was a typo I think, see comment-block for an implementation that works.
This fixes a bug with saying "block" in c-style languages. Before this PR, it crashes. After this PR, it uses the default successfully.

Fix default block implementation

---

.gitignore

As it is currently written, the `.gitignore` file does not properly ignore `.bak`s. It also seems to not properly ignore `.DS_Store`s. Here I add the wildcard character to these patterns to make sure they are correctly matched against.

Update gitignore match rules

---

core/modes/code_languages.py
core/snippets/snippets/commentLine.snippet

#1718 added more snippets. Due to an oversight we are now missing a few language definitions that the snippets are relying on which gives the user errors.

Fix missing language definitions for snippets

---

core/snippets/snippets.py

The latest refactoring to snippets made it so we accidentally used the snippet insertion phrase instead of the wrapper phrase for the wrapper list.

Fix bug with incorrect snippet wrapper phrase

---

core/modes/code_languages.py

The csv snippet in `commentLine.snippet` results in an unknown language error otherwise.
Related to https://github.com/talonhub/community/pull/1729?

Add csv language definition for snippets

---

apps/warp/warp.py

This makes possible using commands like `go tab three`, `go tab final`, `go word left` or `go word right`.

Add Warp context action implementations

---

core/edit/edit.py
core/edit/edit_command.py

I have he left the comment indicating that `edit.delete_all` is beta only so we remember to restore it when it lands in public.

Fix regression with `clear all` not working in talon public

---

core/snippets/snippets_parser.py

Some of the errors from the snippet parser should really be warnings since the snippet still works.

Convert some of the snippet parser errors into warnings

---

core/snippets/snippets/withStatement.snippet

Context managers are fairly frequently used in Python; they're also something of a Python-specfic construct.
For example:
```
with open(filepath) as f:
file_lines = f.readlines()
```
Add context manager statement, used with `snip with` and `with wrap`.
`snip context` is a possible alternative name.

Add snippet for Python context manager

---

plugin/mouse/continuous_scrolling.talon
plugin/mouse/mouse_scroll.py

Allows stopping continuous scrolling with "stop" and "stop here". 
Something worth discussing: should we indicate the grammar change in the continuous scrolling graphical display and if so how? Should we just replace "wheel stop" in the display with "stop" or should we indicate that the word wheel can optionally be used?

Make the word wheel optional for stop continuous scrolling commands

---

.gitignore

We have migrated most of the files that used to be in this directory to be colocated with the .py/.talon implementations of the corresponding features, therefore this is a move to consistency with our policy (in the README) that you should create a fork of community to house your changes and customizations.
Fixes #1732.

Remove /settings from default .gitignore.

---

apps/firefox/firefox.py

On Fedora, I'm unsure why this firefox uses a different app name

Add another match rule to firefox

---

apps/vscode/README.md

- Update links
- Add reference to Andreas Talon (IMO, everyone should be using this one)
- Link directly to settings (friendlier than editing settings.json)
- Don't recommend activating tags on the terminal tag alone (fixes #1723)
- Add option to open integrated terminals as editors

Update Visual Studio Code README.

---

core/user_settings.py

Fixes #1769
[1] https://docs.python.org/3/library/csv.html#id4

Remove additional \r from default generated CSV files on Windows [1].

---

core/snippets/snippets.py

We only used the first character of the variable name. All of the snippets in community uses a single digit that was fine, but if the user used something like `ifStatement.body` we looked for a variable called `b` instead of `body`.
Fixes #1781

Properly support splitting wrapper names with variables

---

lang/python/python.py

I think this operator was overlooked in the migration

implement MATH_INTEGER_DIVIDE for python

---

lang/rust/rust.py
lang/rust/rust.talon

Migrate the existing rust operators and add pointer operators. 
I think that the original
```python
def code_operator_structure_dereference():
actions.auto_insert("*")
```
may be mistaken. I migrated that operator as is because I do not know much about rust.

Migrate rust operators

---

lang/scala/scala.py

This does not migrate the actions in the talon file. 
I am not sure what to do with these
```
op right arrow: " -> "
op left arrow: " <- "
op plus plus: " ++ "
op subtype: " <: "
```
I did add some missing operators.

Migrate scala operators (from the ones defined as actions)

---

BREAKING_CHANGES.txt
lang/php/php.py
lang/php/php.talon

Migrate php operators. I believe this is the final operators migration. I added some missing operators. There are some further operators that might be worth adding, but that might be best left to pull requests from people who understand the language. 
I wonder if adding "is loosely equal" and "is loosely not equal" as aliases might be better than deprecation.

Migrate php operators

---

core/homophones/homophones.py
core/homophones/homophones.talon

I consistently get misrecognitions when trying to hide the homophones picker menu, since "phones hide" sounds a lot like "phone side", which opens another homophones picker menu.
if other people have this problem too, it might make sense to change the defaults. (and unlike most cases of changing spoken commands, I had to dig a bit to get the gui text to match the .talon file)
I also thought of using "phones close", but that's a homophone too 😆

change "homophones hide"=>"homophones exit"

---

apps/vscode/vscode.py

Draft PR to implement https://github.com/talonhub/community/pull/1677#issuecomment-2600944142 properly, such that it only applies in the main editor window (or at least, not in modal/system windows).
TODO:

vscode: copy, paste, redo and undo through command palette (2nd attempt)

---

core/keys/symbols.py

The latter is not consistently recognized in dictation mode with Conformer D.

Add "at symbol" alternative for "at sign".

---

apps/vscode/vscode.py

It just stood out to me that `split_next()` was the only function in this file that calls `vscode_and_wait()`. All other functions, including very similar ones like `split_last()`, call `vscode()`.
If this is in fact correct, just close the PR.

Equalize `vscode_and_wait()` outlier in `vscode.py`.

---

tags/file_manager/file_manager.talon

When used in Windows Explorer, this allows you to think about the name after already having created the folder.

Made `file_manager` tag's "folder new" text optional.

---

apps/opera/opera_win_linux.py
core/windows_and_tabs/window_management.talon
core/windows_and_tabs/windows_and_tabs_linux.py
core/windows_and_tabs/windows_and_tabs_win.py

Following <https://github.com/talonhub/community/pull/1841#pullrequestreview-2813260862>.
- Implemented it for Opera. \[Tested it under Windows.\]
- `windows_and_tabs_mac.py` already implements it generically (which is correct for Opera [\[**proof\]**](https://help.opera.com/en/latest/shortcuts/#browserKeys)).

Made neglected `app.preferences()` available as phrase.

---

core/snippets/snippets/caseStatement.snippet
core/snippets/snippets/commentLine.snippet
core/snippets/snippets/defaultStatement.snippet
core/snippets/snippets/elixir.snippet
core/snippets/snippets/elseStatement.snippet
core/snippets/snippets/genericForLoopStatement.snippet
core/snippets/snippets/ifStatement.snippet
core/snippets/snippets/switchStatement.snippet
core/snippets/snippets/tryStatement.snippet
core/snippets/snippets/whileLoopStatement.snippet
lang/elixir/elixir.py
lang/elixir/elixir.talon

There does not seem to be an else if statement in the language, so I did not try to migrate that action. 
I was not sure what to do about the fact that a switch statement is called a case statement in the language, so changing the code state case action to do what that action usually does would not reflect what things are named in this language. 
There is an issue with actions conflicting with commands with the elixir setup, so I migrated the actions but left the commands alone. 
I followed the structure in the existing talon file of explicitly defining state commands. 
I am not familiar enough with the language to know how to properly handle the import actions, which are currently unusable anyways because they do not correspond to action definitions.

Start migrating elixir to snippets

---

core/snippets/snippets/commentLine.snippet
core/snippets/snippets/functionCall.snippet
core/snippets/snippets/sql.snippet
lang/sql/sql.py
lang/sql/sql.talon

A possible regression is that the space after the close parentheses for the with command is lost when migrated to snippets because a space added to the snippet after the parentheses gets ignored. Based on what I remember about SQL and some quick research, that does not seem consequential, but it may be worth checking with people who use SQL more than I do if this is a regression or not.

Migrate sql to snippets

---

lang/talon/talon.py

This migrates the talon programming code to use the snippet system given that the comment action was the only thing that seemed to need migration.

Use snippet for talon comment action

---

core/snippets/snippets/lua.snippet
lang/lua/lua.py

I put the snippet in the lua file because the try catch statement file requires 2 snippet placeholders. I was not sure how to properly convert this into a snippet due to lack of familiarity with the language, so I just recreated the functionality of the original action and will leave a proper snippet definition to someone more familiar with the language.

Migrate lua try catch

---

core/edit/edit.talon
core/edit/edit_command.py

Fixes #1809 
Permits mapping actions like `bonk: user.edit_command("delete", "wordLeft")`
For now the discoverability of the commands is low, so at some point I will also open a pr to include a doc page on customizing edit actions

Accept string as edit command arguments

---

core/snippets/snippets/forLoopStatement.snippet
lang/c/c.py

This migrates c to use the for loop snippet and uses the version of the snippet with the semicolons.

Migrate c to use for loop snippet

---

core/snippets/snippets_insert_raw_text.py

The raw snippet insert currently reaches the first stop by moving to the correct column, going to the beginning of the line, and pressing right. This can fail when there is indentation at the start of the line by putting the cursor in the wrong position. This pull request addresses this by moving the cursor to the end of the line and then moving left the required number of times.

Have raw snippet insert reach the first stop from the end of the line

---

core/snippets/snippets_insert_raw_text.py

This fixes a bug where columns left would fail to take handle multiple stops on the same line.

Fix snippet raw insert columns left

---

lang/c/c.py

The definition of the c_types capture had an exact duplicate, so this PR removes it.

Remove duplicate c_types capture definition

---

lang/go/go.talon

Go had a list of common functions defined but lacked the appropriate tag activation.

1 Line Bugfix: Fix missing go common function tag activation

---

BREAKING_CHANGES.txt

A few dates were missing a leading 0 or were in YYYY-DD-MM rather than the file's existing convention of YYYY-MM-DD

chore(docs): Normalize date formats in BREAKING_CHANGES to YYYY-MM-DD

---

core/help/help.py

When calling help for a list which happens to be empty (ex: saying "help snip" with no global snippets and outside of a supported language mode), the command fails with "IndexError: list index out of range".

Fix error when trying to display an empty list

---

lang/c/c.py
lang/c/c.talon

I attempt to address at least part of this issue: https://github.com/talonhub/community/issues/853. The c_signed list had the issue of having spaces at the end of its words, which would create an extra space when used by captures not expecting that. I addressed this by removing the extraneous spaces and adding a space at the end of the command consisting solely of the c_signed capture. 
I have not done c programming in ages, so I would appreciate it if someone actually using this grammar could test to see if this breaks anything before it gets merged.

Address c signed spacing

---

core/help/help.py

- Display "List: " at the beginning and pagination in parentheses to match other help displays
- Display the list description (wrapped to 70 characters if needed)
- Display "empty" instead of "1/0" if the list is empty
Before:
After:

Improve list help display

---

lang/c/c.py

This can be tested with the following c.talon command: standard cast to <user.stdint_cast>: "{stdint_cast}"
example: `static cast to you int` gives `(uint32_t)`
Another change based on chdoc's c++ pull request.

Add alternative for unsigned

---

core/snippets/snippets_insert_raw_text.py

Applies when:
- there is text on the line after the inserted snippet
- the first stop in the snippet is on the last (or only) line
Also documents an assumption in `move_to_correct_column` that caused the incorrect behavior.
Per discussion on Slack, we may want to change the behavior of `move_to_correct_column` to not go to the end of the line, but this involves different tradeoffs that should be discussed further.

Properly position the cursor at the first stop in some cases when inserting snippets without editor support

---

core/keys/symbols.py

Given how common semicolons are in programming, I believe we should have a shorter standard form in command mode. Note that the old spoken form is for dictation mode and command mode but the new spoken form is only added to command mode.

Add shorter form for semicolon
