talonhub/community

- README.md
Hopefully someone finds them useful :)
> Some docs of what I know so far

- misc/git.talon
Regex the terminal name as Mac/linux will have all kinds of terminal names hopefully this covers most of them
> Add git support via talon file

- code/win/edit.talon
- text/generic_editor.talon
And fix clear way left to delete stuff :)
> Linux text editing support

- code/linux/apps/firefox.talon
A couple of shortcuts are different to Windows (e.g. open bookmarks)
so make it it's own file
> Linux firefox commands

- misc/git.talon
Missed a couple common git commands
> Git status + log

- apps/linux/terminal.talon
- apps/mac/terminal.talon
Got refactored, now it works again plus can open a new window
> Fix path to modifier_key function + new window

- apps/mac/slack.talon
- apps/win/slack.talon
- misc/git.talon
> Git and slack updates

- code/jetbrains.py
> Update for new capture format

- code/jetbrains.py
To be cross platform the nonce file has been changed to home dir
Looking in tmp means we can support both versions
https://github.com/anonfunc/intellij-voicecode/pull/5
> Update for new version of plugin

- apps/jetbrains.talon
- code/ide.py
- misc/ide.talon
So we implement less ourselves
> Use new global actions

- apps/linux/terminal.talon
- misc/git.talon
Made the git pull/push commands flow better
Bit of navigation for the terminal
> Minor Git and terminal updates

- apps/jetbrains.talon
- apps/linux/terminal.talon
- misc/git.talon
- misc/ide.talon
- misc/tabs.talon
talon has switched from match to find for regexes a few versions ago
> remove obsolete .* in matches

- README.md
- apps/jetbrains.talon
- apps/mac/slack.talon
- apps/win/slack.talon
- code/formatters.py
- misc/formatters.talon
- misc/standard.talon
according to talon overloard phrase has fully replaced dgndication
> replace obsolete dgndication by phrase

- code/keys.py
- misc/keys.talon
This also adds symbols to modifiers, like `cmd-~` and `cmd-,`
> Add F# keys, like F1

- code/formatters.py
- lang/go.talon
This is essentially a direct port of https://github.com/anonfunc/talon-user/blob/24084094b1a145649ee885a3746c451ed7d9353b/lang/language.py#L179-L386 which I have been using for a while to write Go code. I just switched to knausj_talon on Friday so spending the weekend getting this ready for Monday :)
> Add GoLang code support

- README.md
- use consistent / in paths (maybe there should be a separate section for windows?)
- home directory anchor is nice `~/`
- add section for wav2letter setup
> minor edits to setup instructions

- code/jetbrains.py
As per latest (soon to be released) voicecode plugin
> Allow hidden files to contain the nonce

- apps/file_manager.talon
- code/file_manager.py
Folder list isn't refreshed as it needs a fix in talon. A little bit of formatting too
> Enable directory switching in linux terminal

- code/jetbrains.py
Now it should work on Windows/Linux/MacOS and with older and newer versions of the plugin
> Cross platform tmp dir

- apps/mac/terminal.talon
Add reverse search and kill commands for mac. This is a bit duplicative. Let me know if there is a convention for doing this better.
> Add reverse search and kill commands

- lang/python.talon
Sorry about the auto-trimming of whitespace - do you want to leave it in?
> Add python support for docstrings and pytest

- apps/linux/teams.talon
only tested on linux but i suspect the windows shortcuts are the same
> support microsoft teams messenger

- apps/linux/outlook.talon
this should also be the same on windows but again have not tested it. this is also another web application that could eventually go into a web folder.
> add support for outlook web application

- apps/linux/termite.talon
i suppose some of these are probably just generic for linux terminals
> add support for the termite terminal

- apps/linux/dunst.talon
this is a linux notification manager that you just interact with on the desktop
> basic dunst commands

- code/exec.py
i feel like enough people are using this (or something similar) that it probably warrants being in the actual branch. not sure if there is a reason it wasn't included yet.
i use it for calling notify-send.sh to issue dunst notifications on state changes, etc for instance.
> function to execute system commands

- code/mouse.py
Option to hide or show the GUI when activating wheel gaze
> add scroll gui option

- apps/linux/vscode.talon
- apps/vscode.talon
- apps/vscode_generic.talon
- apps/win/vscode.talon
- misc/git.talon
- misc/tabs.talon
Thank you @khornlund for the initial base work implementing vscode The following commits enable Visual Studio Code functionality to work in windows.
I am unable at the moment  to prove this does not break for linux. I imagine the same functionality would also be suitable for MAC but also unable test for MAC so have not added
> Fix vscode windows

- code/mouse.py
On linux and presumably other non-windows os's this import will fail and break things.
> Fix non-windows os's

- code/ordinals.py
i realized time I updated ordinal I broke 'first', this fixes that as well as auto pep8 cleanup via black
> fix broken first ordinal plus pep8 cleanup

- text/symbols.talon
a couple more things I always use that I imagine other people will use to
> symbols.talon: a couple more string symbol commands

- lang/comment.talon
- lang/talon.talon
Just a consistency on quotes in insert and some useful voice commands to make key chord composition easier
> Language additions for Talon Files, key chord voice commands

- lang/javascript.talon
Converted this over to the standard programming actions. Let me know if anything should be adjusted!
> Add JavaScript language implementation

- apps/linux/taskwarrior.talon
planned to make this into something way more robust but I haven't had time so i am just pushing what I have, since I know at least a few other people are using to task warrior
> initial task warrior support

- apps/linux/tmux.talon
- code/firefox.py
- code/gdb.py
- code/tags.py
Not sure if prefixing every command with mux is a good idea?
> Add tmux commands to use in terminal

- code/switcher.py
-Needed to add a .lower() to get anything to focus on mac
-I haven't tested this on Windows/Linux.
> fix the switcher not focusing anything on mac

- code/exec.py
this adds a command to fork stuff off without stalling talon if it's not something that will finish right away. it may be better to actually just call it `_nonblock` vs `_nb`
> non blocking command execution call

- code/code.py
- lang/block_comment.talon
- lang/c/c.py
- lang/c/c.talon
this is a merging of my and @ma-anwar C stuff I've been using. is not perfect, as with everything I push it seems lol, but should be enough to get people going
> basic c lang support

- code/abbreviate.py
the one contentious one might be 'funny' to 'lol', but I am tempted to start adding acronyms another generic shortening into this as well rather than only strictly abbreviations, because it seems like the natural place to do it...
> more abbreviations

- lang/batch.talon
this is just stuff I used quick while I was recently scripting, but for now don't have time to add full blown abstraction stuff
> very basic batch scripting stuff

- apps/vscode/vscode.talon
Found select more and less commented out using the new system. Changed to editor actions and updated comment.
> Fixed WTF expand/shrink section

- apps/linux/guake.talon
Add talon implementation for [guake](http://guake-project.org) terminal
It's been a few months since I've worked on talon scripts so let me know if I've missed some part of best practice
> Add guake.talon

- code/code.py
- lang/programming.talon
- lang/python/python.talon
Apologies if this already exists elsewhere!
> Add docstring command

- code/formatters.py
- misc/formatters.talon
At dweil's request, a simple implementation of nested punctuation & chained (separate) formatters. 
(Details of each change in the commit messages)
Closes #238
> Better formatters

- code/mouse.py
fix a few errors is noted by aegis. is not tested because I don't have windows
> fix unescaped back slashes

- apps/jetbrains/jetbrains.py
- apps/jetbrains/jetbrains.talon
Various additions for Jetbrains (and some changes) I've pulled from @dwiel's config at his request. I don't have the Jetbrains RPC stuff set up, so it may be worth someone who uses Jetbrains testing these first.
> Various Additions for Jetbrains

- apps/mac/desktops.py
- apps/mac/desktops.talon
I've extracted these from @dwiel's config at his request. I don't have a mac so it might be worth testing these before merging.
> Add desktop movement commands for Mac

- text/symbols.talon
> Change this to that for consistency when referring to the current selection.

- code/history.py
- settings.talon
Making these settings makes them easier for users to change.
> add settings for command history size

- lang/talon/talon.talon
It's just a typo. But I guess it's a fix :-).
> 1-aedison: fix command name bug

- code/switcher.py
Hi, my first bug fix for a public repo here. Let me know if you need me to do anything more.
> 1-aedison: bug fix for switching less than three characters

- apps/discord/discord.mac.talon
> Typo fix in discord key commands

- code/mouse.py
(and eye tracker is present). (#419)
> Automatically enable 'control mouse' when 'wheel gaze' is enabled

- apps/vscode/README.md
- apps/vscode/command_client.py
- apps/vscode/vscode.py
- apps/vscode/vscode.talon
This PR changes knausj to communicate with talon using the [VSCode command server extension](https://marketplace.visualstudio.com/items?itemName=pokey.command-server).  See new README for more details
> Add VSCode command-client

- settings.talon
I was having quite a bit of trouble reading the settings, so added whitespace between settings
> [Minor] Make settings more readable

- apps/file_manager.talon
As an alternative to existing 'daddy' file navigation command
> Add 'go parent' command to talon community

- code/keys.py
For those of us who aren't North American and are more more comfortable with the term "full stop"
> Add full stop command to talon

- code/formatters.py
Split existing camelCase text before reformatting.
> Upd formatter to support reformatting of camel case

- apps/jetbrains/jetbrains.py
The changes allow `jetbrains` context to take effect for the Android Studio app
> Jetbrains: Added android studio support

- modes/wake_up.talon
This way user doesn't need to pause after saying sleep command; they can start
talking to someone else.
> Add optional phrase after sleep commands

- code/keys.py
Really useful when dictating currencies and semantic versions, eg 'three point four point twenty"
> Add point symbol

- misc/cancel.talon
- "cancel" allows you to cancel a command that you realize you are flubbing, eg "air bat crap cancel"
- "ignore" allows you to say something (eg to a human) that you don't want talon to hear, eg "ignore hey Jerry"
> Add "cancel" and "ignore"

- apps/jetbrains/jetbrains.py
- apps/platforms/win/notepad++/notepad++.py
- apps/platforms/win/powershell/power_shell.py
Some windows apps broke with the recent .talon -> .py transition.
> Fix windows regressions

- misc/cancel.talon
> added explanation for cancel and ignore

- code/create_spoken_forms.py
- for numbers in the range [1000, 9999]
- plus some other unrelated cleanup
> Create spoken form for years

- apps/talon_repl.talon
- code/talon_helpers.py
- lang/talon/talon.py
- lang/talon/talon.talon
- misc/talon_helpers.talon
- #387
- some initial repl support
> Add commands for debugging, and more easily dictating talon files

- code/edit.py
- text/homophones.talon
useful for applying homophones to the word left of/right of/at cursor
> add phones word/word left/word right commands

- apps/platforms/win/windows_terminal/windows_terminal.py
- apps/platforms/win/windows_terminal/windows_terminal.talon
synonyms:
buffy - "buffer search"
queer eye - pun on 'query'
> Implement edit.find for windows terminal.

- code/cancel.py
This is a new and improved pull request for this change....
Sometimes the 'text' key does not exists, maybe only during sleep mode.
> Fix KeyError bug.

- apps/jetbrains/jetbrains.py
WebStorm didn't activate the jetbrains context on Windows.
> Fix jetbrains context

- README.md
I know it's embarassingly obvious in hindsight, but it didn't occur to me for days and resorted to searching on the slack. Hopefully this helps others like me!
> Explained how to type a capital letter

- code/homophones.py
- text/homophones.talon
> Add phones exit button and make all phones options clickable

- code/code.py
- lang/programming.talon
- lang/r/r.py
- lang/r/r.talon
Might be useful for common named arguments in python too
> Support named arguments for r

- code/create_spoken_forms.py
> Fix bugs in create_spoken_forms

- code/code.py
- lang/java/java.py
- lang/java/java.talon
- lang/operators.talon
* Add all types for java
* Add more operators for java
* Add modifiers for java
* Add shortcuts for methods
* Add arrays
> Add better support for the java programming language

- apps/edge/edge.py
- apps/edge/mac.py
As of today, on Intel Macs anyway.
> Correct bundle name for the edge browser on mac

- code/mouse.py
- misc/mouse.talon
- settings.talon
- Make wheel tiny amount relative to setting (what fraction should this default to?)
- Add setting for wheel left/right amount
> Make wheel tiny amount relative to setting

- apps/web/github.talon
- apps/web/gitlab.talon
- apps/web/twitter.talon
- apps/web/window_titles.md
- code/browser.py
Should work with any addon for any browser that displays the whole url in the window title.
> Parse url from browser title

- code/window_snap.py
I tested this with two 16:9 screens. Maybe the difference between dpi zoom levels should be taken into account in the future. One additional test combining 16:9 and 4:3 would also be nice.
> Improve snap to vertical screen

- apps/platforms/mac/sarafi/safari.py
correcting the shortcuts for safari
> fix safari shortcuts

- code/switcher.py
Remove the need to utilize the start menu for launching apps
> [Windows] Improve app launching

- code/formatters.py
These have been sitting around, commented out for a while, let's remove them to tidy up the code base a bit.
> Clean up unused formatters

- code/mouse.py
- misc/mouse.talon
- misc/mouse_cursor.talon
- settings.talon
> Put curse yes/no commands behind tag (disabled by default)

- mouse_grid/mouse_grid.py
> Improve code call style in mouse_grid.py

- code/formatters.py
Removes a couple of old formatter implementations which no commands map to any longer.
> Remove unused formatter implementations

- lang/tags/function_selector_open.talon
- lang/tags/functions_gui.py
- lang/tags/functions_gui_open.talon
- lang/tags/libraries_gui.py
- lang/tags/library_gui_open.talon
- lang/tags/library_selector_open.talon
These were added in #699 but lost in the language refactorings merge.
> Add back close buttons to language imgui popups

- code/dictation.py
- modes/dictation_mode.talon
Allows user to say "numb" followed by a number within prose and have it formatted in decimal.
> Support numbers within prose.

- code/formatters.py
As requested here: https://github.com/knausj85/knausj_talon/pull/729/files#r782138064
> Add comment to SEP and NOSEP variables

- code/dictation.py
- code/formatters.py
- code/vocabulary.py
> override dictate.replace_words instead of defining user.replace_phrases

- code/formatters.py
Small cleanups/rewrites, no functionality change. Gonna merge this in a week unless someone objects.
> formatters.py: reorg/simplify a bit

- code/screenshot.py
> Refactor default screenshot_selection implementation

- code/code.py
- lang/rust/rust.py
- lang/rust/rust.talon
- modes/language_modes.talon
Added initial support for Rust.
> Add Rust support

- apps/visualstudio/visual_studio.py
- apps/visualstudio/visual_studio.talon
- apps/visualstudio/win.py
Adds vs2022 to app name check. Removes unnecessary app name bits from context checks
> Adds VS2022 Support

- .github/workflows/ci.yml
This runs the tests we have (per https://github.com/knausj85/knausj_talon#automated-tests) in CI using GitHub Actions.
> Run pytest on GitHub Actions for CI

- README.md
Documenting how to add additional settings to make the more discoverable for new users. Addresses https://github.com/knausj85/knausj_talon/issues/832
> Documenting additional settings

- code/code.py
- lang/css/css.py
- lang/css/css.talon
This adds some basic CSS support. It intentionally does not add support for the entirety of CSS, rather opting to include in lists things I have used in the past or anticipate on using.
Opening this to gauge how people feel about this approach. I see several people have been writing their own CSS support for a while. Figured I'd make a PR with something that should be maintainable in the long term.
> Add basic CSS support

- code/switcher.py
> remove unnecessary initialization of lists to empty

- lang/typescript/typescriptreact.talon
looks like a good case for adding this inheritance
> add javascriptreact tag to typescriptreact

- code/formatters.py
> "all caps" => "all cap"

- code/switcher.py
> #839  Use time.perf_counter, not time.monotonic

- code/code.py
- lang/sql/sql.py
- lang/sql/sql.talon
- lang/tags/operators_math.py
- lang/tags/operators_math.talon
> SQL language support, no longer DataGrip-specific.

- draft_editor/draft_editor.py
- draft_editor/draft_editor.talon
> Improve VSCode draft editor robustness

- code/formatters.py
I think this code is dead. Plan is to comment it out and remove it later if it doesn't cause problems.
> formatters.py: no more "over"-removal

- .pre-commit-config.yaml
See https://github.com/knausj85/knausj_talon/pull/771#issuecomment-1172901164
> pre-commit: Fix EOF before line endings

- code/keys.py
- text/symbols.talon
This resolved some recognition issues for me, and seems to follow the general rules of thumb that I've heard to improve recondition.
> symbols: Add spaces in under score and down score

- lang/ruby/ruby.talon
- misc/git.talon
- misc/standard.talon
- text/symbols.talon
use `user.insert_between` more often to compact code.
> Insert between more

- lang/go/go.talon
> go.talon: remove number in spoken form

- lang/rust/rust.talon
> lang/rust/rust.talon: fix semicolon

- lang/tags/comment_block.talon
> lang/tags/comment_block.talon: use spaces for indentation

- code/create_spoken_forms.py
- code/help.py
- code/numbers.py
- code/vocabulary.py
https://github.com/knausj85/knausj_talon/issues/922
> create_spoken_forms, help, numbers: fix typing

- modes/wake_up_wav2letter.talon
Add "wake up" and "go to sleep" as better-recognized synonyms for "talon wake" and "talon sleep" if we're under wav2letter.
> under w2l, add "wake up" and "go to sleep" commands

- README.md
Addresses https://github.com/knausj85/knausj_talon/issues/994 and spruces up a few places where the readme has gotten out of date.
> fix README.md after refactoring from #897

- apps/vscode/vscode.py
* Use heuristic to improve compatibility with "copy entire line if no selection" setting
*  Fix slap command if cursor is already at end-of-line and a completion popup is open.
> VSCode: improve actions `selected_text` and `line_insert_down`

- core/modes/dictation_mode.talon
- core/text/text_and_dictation.py
Fixes https://github.com/knausj85/knausj_talon/issues/1005. Needs to be tested.
> dictation mode: use dictation_insert instead of overridding auto_insert

- apps/git/git_arguments.csv
> add git argument --force-with-lease

- core/edit/edit.py
- core/edit/edit.talon
- tags/terminal/readline.py
In order to implement this, I had to move some of the cut and copy actions into their own functions (this is related to https://github.com/knausj85/knausj_talon/issues/1015).
> Add more commands to readline tag

- core/homophones/homophones.py
- core/homophones/homophones.talon
> make "phones that" select a word if nothing is selected.

- core/keys/keys.py
thanks a bunch to @gsingh93 for the inspiration (from #1048)
> turn alphabet into a list grabbed from a csv file

- README.md
- Cleans up overview
- Cleans up installation instructions
- Adds links to Rango, Cursorless and other repos
- Cleans up getting started section
> Rework main README intro

- core/file_extension/file_extension.py
https://github.com/knausj85/knausj_talon/pull/1071#pullrequestreview-1230696499
> extensions: fix .flac

- apps/vscode/command_client/command_client.py
- apps/vscode/command_client/vscode.py
> Rework vscode-specific command client code

- core/homophones/homophones.py
Fix typo in homophone help message.
> Fix typo in homophone help message

- core/mouse_grid/mouse_grid.py
- plugin/mouse/mouse.py
- plugin/mouse/mouse.talon
Address #919: Remove imports of talon_plugin; use new tracking actions.
> Address #919

- core/mouse_grid/mouse_grid.py
- plugin/mouse/mouse.py
> use Control Mouse rather than Legacy with tracking.* actions

- plugin/mouse/mouse.py
Address #1094 
-  correct merge error, restore import of eye_zoom_mouse 
- comment cleanup
> Address #1094

- lang/talon/talon.talon
- plugin/talon_helpers/talon_helpers.py
- Add command to require a particular host in talon files
- Add new action talon_get_hostname() to retrieve hostname
> Add command to require a particular host in talon files

- plugin/symbols/symbols.talon
> remove "new line" "carriage return" and "line feed", confusing

- core/keys/keys.py
> move "grave" out of dictation mode

- core/modes/wake_and_sleep.talon
- core/modes/wake_and_sleep_wav2letter.talon
> allow repeats of all wake up commands

- core/text/text.talon
I have found this command very useful even though we already have 'title' command.  Just, like how the 'word' command is useful in addition to the 'say' command.
> add 'proud' command for inserting capitalized word

- plugin/screenshot/screenshot.py
- plugin/screenshot/screenshot.talon
I don't have access to any other graphical operating systems to test they could do this.
> add `grab selection clip` for MacOS and windows - grab a selection of screen to clipboard

- CONTRIBUTING.md
- README.md
Let's document our desired approach to updating the grammar and such; based on the conversation on https://github.com/knausj85/knausj_talon/pull/1109 and stuff we previously agreed to in the distant past
> Create initial contributing document

- apps/i3wm/i3wm.py
- apps/i3wm/i3wm.talon
Need to test this first but opening to get the ball rolling.
Starts on #945
> i3wm: Call i3-msg using subprocess instead of os.system

- tags/browser/browser.py
This refactors the `browser.address` implementation to be clearer, making the following changes along the way:
- The same word is no longer checked to be a valid URL twice.
- Check the first word is a URL before checking the rest of the words in reverse. The suggested Firefox extension prepends the URL to the window title (and does not wrap it in brackets).
- Avoid checking the empty string, in case a webpage has consecutive spaces in its title.
> browser: Simplify title address extraction

- core/edit/edit.py
- core/edit/edit.talon
`"copy start of line"`
`"clear end of line"`
`"paste line"`
`"paste word"`
`"drink line"`
`"pour line"`
Made sure all operations(select, copy, cut, paste, delete) had implementations for all, line, line start, line end, and word. Grouped a few commands to make finding then easier and added actions for reusable logic.
> Added additional edit commands

- core/help/help.py
- core/help/help_open.talon
- core/help/help_scope.py
- core/help/help_scope_open.talon
- core/modes/language_modes.talon
- help_scope and help modes converted to tags
- Removed old commands for enabling gdb mode
> more mode cleanup

- apps/git/git_arguments.csv
for `git pull --no-rebase` so you can merge even if you have rebase as the default for pull
> git_arguments.csv, add --no-rebase

- plugin/repeater/repeater.talon
`repeat phrase <N> times` initially from https://talonvoice.slack.com/archives/C9MHQ4AGP/p1679478692465999
I'm not entirely sure if we should have `again` on its own as a command, but would love to know everyone's thoughts.
> repeater: Add repeat phrase commands

- core/file_extension/file_extension.py
Java developers.  There are dozens of us, dozens!
> add {java, class, log} file extensions

- core/websites_and_search_engines/websites_and_search_engines.talon
These have been super useful for me.
> add {open paste, open that, search engine paste} commands

- lang/java/java.py
These are really implemented below:
https://github.com/knausj85/knausj_talon/blob/38cb583db62593165c9938dd481b5f2b159e4d53/lang/java/java.py#L262-L264
https://github.com/knausj85/knausj_talon/blob/38cb583db62593165c9938dd481b5f2b159e4d53/lang/java/java.py#L282-L283
https://github.com/knausj85/knausj_talon/blob/38cb583db62593165c9938dd481b5f2b159e4d53/lang/java/java.py#L300-L301
> java: Remove shadowed function action impls

- .pre-commit-config.yaml
More information on the issue this is working around:
https://github.com/Lucas-C/pre-commit-hooks/issues/83
> Update minimum pre-commit version to 3.2.0.

- core/app_switcher/app_switcher.py
`"focus firefox"` => focuses first window of firefox
`"second"` => cycles to next window
This is even more beneficial if you have a repeater noise
> Call action window next when refocusing current application

- apps/vscode/vscode.py
It would appear that the vast majority of the commands in vscode.talon do work in Azure Data Studio when applicable.
> Support for Azure Data Studio to work with Cursorless

- apps/vscode/vscode.talon
- It makes sense to have a redo since there is an undo
> Add curse redo command

- plugin/symbols/symbols.talon
@nriley said this was a good idea in Slack.
> symbols.talon: s/ellipses/ellipsis/

- apps/emacs/emacs.py
- apps/mintty/mintty_win.py
- apps/tmux/tmux.py
- core/deprecations.py
- core/help/help.py
- core/help/help_scope.py
- core/mouse_grid/mouse_grid.py
- core/snippets/snippets.py
- core/text/text_and_dictation.py
- core/windows_and_tabs/window_snap.py
- plugin/command_history/command_history.py
- plugin/draft_editor/draft_editor.py
- plugin/mode_indicator/mode_indicator.py
- plugin/mouse/mouse.py
- plugin/paste_to_insert.py
- plugin/screenshot/screenshot.py
- plugin/text_navigation/text_navigation.py
- tags/file_manager/file_manager.py
Builds on #1349 by converting most uses of `setting = mod.setting()` in community to `settings.get()`.
@lunixbochs, would appreciate a quick look to make sure this is correctly using settings.
> Use settings.get() in more places

- apps/firefox/firefox.py
as I tend to use the forks LibreWolf and Waterfox I added the app names to make use of the commands already available from Firefox
> added Firefox forks LibreWolf and Waterfox

- README.md
- core/modes/sleep_mode.talon
Fixes a typo in https://github.com/talonhub/community/pull/1360
> Revert changes to `user.mouse_enable_pop_click`

- .pre-commit-config.yaml
See https://github.com/psf/black/issues/3405
> Switch to black pre-commit mirror

- settings.talon
Just learned that dark_mode exists, would like to have an easier settings option for users.
> feat: Add dark_mode option in settings

- settings.talon
This is such a common question people have. I definitely believe we should make it easier for them.
> Add speech timeout to settings file

- tags/file_manager/file_manager.py
Also bugfix the clearing of the current page numbers.
> file_manager: Check tag before querying current path

- apps/finder/finder.py
- apps/nautilus/nautilus.py
- apps/powershell/powershell_win.py
- apps/windows_command_processor/command_processor_actions_win.py
- apps/windows_command_processor/command_processor_win.py
- apps/windows_explorer/windows_explorer.py
- core/navigation/navigation.py
- core/navigation/navigation.talon
- tags/browser/browser.talon
- tags/file_manager/file_manager.py
- tags/file_manager/file_manager.talon
This implements standardized go back and go forward voice commands as well as matching actions to be used in applications system wide
> Unify go back and go forward implementations

- apps/vscode/vscode.py
> Move vscode mac definition to edit namespace

- core/text/formatters.py
Accidentally renamed an action in a previous pull request. Restoring
> Restore reformat_text

- apps/vscode/vscode.py
I've been using cursorless with Cursor the last few weeks with this.
> Update vscode.py to include Cursor for Linux as an option

- .gitignore
Reference
https://talonvoice.slack.com/archives/C9MHQ4AGP/p1725258422426479
> Git ignore .bak files

- migration_helpers/migration_helpers.py
See discussion starting at https://github.com/talonhub/community/pull/1268#issuecomment-2325721706
> Display message when encountering core Talon issue with ready callback.

- apps/brave/brave.py
- apps/calibre/calibre.py
- apps/chrome/chrome.py
- apps/edge/edge.py
- apps/emacs/emacs.py
- apps/firefox/firefox.py
- apps/jetbrains/jetbrains.py
- apps/notepad++/notepad++_win.py
- apps/okular/okular.py
- apps/opera/opera.py
- apps/slack/slack.py
- apps/thunderbird/thunderbird.py
- apps/vivaldi/vivaldi.py
- apps/vscode/vscode.py
- apps/windows_explorer/windows_explorer.py
- core/application_matches.py
> Update more app.exe matching to work with both public and beta Talon.

- lang/kotlin/kotlin.py
- "Companion object" is Kotlin for "static"
- "when" means switch in Kotlin
> Add some Kotlin types and fixed switch

- lang/elixir/elixir.py
- lang/elixir/elixir.talon
> Ran into an error trying to use function handling

- plugin/talon_helpers/talon_helpers.talon
Command for opening debug window:
> Add talon open debug

- lang/c/c.py
- lang/python/python.py
- lang/tags/operators_bitwise.py
- lang/tags/operators_bitwise.talon
- lang/tags/operators_math.py
- lang/tags/operators_math.talon
Add the unary operator not and bitwise not.
Initially implemented in C & Python simply because I use those the most
Surprised this wasn't implemented previously, not sure if there was a reason why
> Add not operators

- plugin/mouse/mouse.py
- plugin/mouse/mouse_cursor.py
- plugin/mouse/mouse_cursor.talon
mouse.py is to large. I have extracted all the hide/show mouse cursor code into a separate python file.
> Refactor hide mouse cursor code

- core/numbers/numbers.py
> Support double digit number small

- plugin/draft_editor/draft_editor.py
Make submission of draft editor more reliable
Don't close the draft if we didn't manage to get the document text
> Make draft editor more reliable

- core/modes/code_languages.py
- core/modes/language_modes.py
- core/snippets/snippets.py
> Extract code languages into separate file

- core/text/formatters.py
- test/test_formatters.py
> Support leading whitespace in formatters

- core/numbers/numbers.py
- core/numbers/numbers.talon
- core/numbers/numbers_prefixed.talon
- core/numbers/numbers_unprefixed.talon
- core/text/text_and_dictation.py
Makes numbers more consistent between prose formatters and the global number command. 
Increase consistency and additional delimiters for different locales
Fixes #1245
> Make numbers more consistent

- core/help/help.py
- core/system_paths.py
- lang/tags/functions_common.py
- lang/tags/libraries_gui.py
- plugin/talon_helpers/talon_helpers.py
> Added action to get active Talon list

- plugin/draft_editor/draft_editor.py
- plugin/draft_editor/draft_editor.talon
> Added tag for draft editor application running

- core/text/formatters.py
> Don't show re formatters in formatter help

- core/edit_file.talon-list
- core/edit_text_file.py
- core/edit_text_file.talon
- core/edit_text_file/edit_text_file.py
- core/edit_text_file/edit_text_file.talon
- core/edit_text_file/edit_text_file.talon-list
Tested on windows and works fine
> Cleaned up edit text file

- core/text/text.talon
Have been superceded by the word formatter list
> Remove duplicate word command

- plugin/cancel/cancel.py
Mimic and sometimes Dragon don't have this key.
> More robust cancel that checks `_ts`

- plugin/cancel/cancel.py
Accidentally used `getattr` instead of `dict.get`
> Fix bug in cancel code

- plugin/mouse/mouse_scroll.py
> Remove `/ 10` from the scroll speed calculation

- settings.talon
https://github.com/talonhub/community/pull/1642 changed the default in the python file, but we missed the default in the settings file
> Change mouse_continuous_scroll_amount setting

- README.md
Small PR - Commit a09ddf8f954370298e3e2d69fbb37415da5704fe moved `formatters.py`. This PR adjusts sources to changes. It also fixes a typo along the way.
> Update `formatters.py` reference

- apps/wsl/wsl.py
- core/user_settings.py
>  Update comments referring to community as Knausj

- apps/visualstudio/visual_studio.py
- apps/visualstudio/visual_studio.talon
- apps/visualstudio/visual_studio_win.py
The Vishal studio files was a bit weird with dupduplicatest context definitions and unnecessary operating system requirements. 
Once I was there I also removed some unnecessary comments and dead code.
> Cleaned up visual studio files

- apps/jetbrains/jetbrains.py
Allow the Voice Code Idea plugin to recognize PhpStorm
> Add new bundle string for PhpStorm 2024.3.2 on Windows

- apps/jetbrains/jetbrains.talon
I fixed three commands that were incorrectly calling the wrong function.
> Fix not working commands in jetbrains.talon file

- core/vocabulary/edit_vocabulary.talon
- core/vocabulary/vocabulary.py
- Fixed duplicate handling.
- Only escape written form when needed.
> Added "check vocab" command and some other vocabulary improvements.

- core/snippets/README.md
- core/snippets/snippet_types.py
- core/snippets/snippets_parser.py
Support a description field in snippet files
> Support description in snippets

- core/homophones/homophones.csv
This adds new homophones to the list in `homophones.csv`. It also sorts the list such that each line has its entries ordered alphabetically, and the lines themselves are ordered alphabetically. The ordering is done case-insensitively.
> Add to homophones

- plugin/mouse/mouse_scroll.py
This allows the wheel stop command with the updated grammar with gaze scrolling.
> Activate continuous scrolling context with wheel gaze

- lang/lua/lua.py
- lang/lua/lua.talon
- lang/tags/operators.py
- lang/tags/operators_math.talon-list
I added the missing exponentiation operator and added a new operator to the original operators definition for floor division.
> Migrate lua operators

- lang/python/python.py
I'm not sure if this is where these belong,  but I figured I'd ask via merge request rather than  via a post to slack  :-)
> add assert and pass to python's user.code_keyword

- core/snippets/snippets_parser.py
> Improve parsing of snippet variables

- lang/ruby/ruby.py
Migrate the ruby operators and add some missing ones.
> Migrate ruby operators

- core/windows_and_tabs/README.md
- core/windows_and_tabs/window_layout.py
- core/windows_and_tabs/window_split_positions.talon-list
- half is easier to pronounce than halves
> Swap halves for half

- lang/c/c.talon
- lang/python/python.talon
- lang/r/r.talon
- lang/rust/rust.talon
- lang/stata/stata.talon
user.code_toggle_libraries() was removed but the references to it were not fully cleaned up
> removed obsolete references to user.code_toggle_libraries()

- plugin/talon_helpers/talon_helpers.py
- plugin/talon_helpers/talon_helpers.talon
Analogous to "talon copy title".
> Added "talon copy win class name" phrase.

- core/snippets/snippets/commentLine.snippet
- lang/batch/batch.py
Migrate the line comment action to use a snippet
> Migrate batch to snippets

- core/snippets/snippets/caseStatement.snippet
- core/snippets/snippets/genericForLoopStatement.snippet
- core/snippets/snippets/import.snippet
- lang/java/java.py
I added a generic for loop snippet and changed the case snippet to be more consistent with the original code action.
> Start migrating java to snippets

- core/snippets/snippets/commentLine.snippet
- core/snippets/snippets/elseIfStatement.snippet
- core/snippets/snippets/elseStatement.snippet
- core/snippets/snippets/functionDeclaration.snippet
- core/snippets/snippets/ifStatement.snippet
- lang/vimscript/vimscript.py
There is a lot of missing functionality for the language, but I will leave adding that to someone more familiar with the language.
> Migrate vim to snippets

- core/snippets/snippets/caseStatement.snippet
- core/snippets/snippets/classDeclaration.snippet
- core/snippets/snippets/commentLine.snippet
- core/snippets/snippets/defaultStatement.snippet
- core/snippets/snippets/elseIfStatement.snippet
- core/snippets/snippets/elseStatement.snippet
- core/snippets/snippets/forEachStatement.snippet
- core/snippets/snippets/functionDeclaration.snippet
- core/snippets/snippets/ifStatement.snippet
- core/snippets/snippets/import.snippet
- core/snippets/snippets/switchStatement.snippet
- core/snippets/snippets/ternary.snippet
- core/snippets/snippets/unlessStatement.snippet
- core/snippets/snippets/untilLoopStatement.snippet
- core/snippets/snippets/whileLoopStatement.snippet
- lang/ruby/ruby.py
I was not sure what to do with "state do" given the diverse uses of the word do in the language and my lack of familiarity with ruby.
> Mostly migrate ruby to snippets

- README.md
> Use keyboard element tags

- tags/file_manager/file_manager.py
Addresses: https://github.com/talonhub/community/issues/1090
> Use scope instead of registry in file_manager.py

- core/edit/edit.talon
This addresses issue 1856: https://github.com/talonhub/community/issues/1856
> Add paste it as alternative to paste that

- lang/tags/keywords.py
Better handle keyword spaces with the keyword grammar. Addresses part of issue #1942.
> Better handle keyword spaces

- core/snippets/snippets/classDeclaration.snippet
Taken from chdoc's larger pull request as I think this can be uncontroversially merged as is an does not need to wait for further c++ functionality.
> Add c++ class declaration snippet

- core/snippets/snippets/structDeclaration.snippet
Another small PR based on chdoc's larger pull request.
> Add c++ struct snippet

- core/modes/code_languages.py
- core/snippets/snippets/communitySnippets.snippet
- core/snippets/snippets_parser.py
My current approach to allowing `---` in a snippet was ad hoc (improvised) and could use improvement.
> Add snippet snippets
